%% HR-GGM parameter-selection validation
% Evaluates saved parameter scans for observed variables O, a hidden master
% regulator H, and a hidden global variable G. Ground truth is used only
% for post hoc validation. Dataset folders are beside this script.
% Exported headers use current manuscript terminology; the original
% dataset naming pattern is retained for input compatibility.

clear;
clc;
close all;


%% Analysis settings
% Resolve the analysis root directory from the script location.
script_file = mfilename('fullpath');

if isempty(script_file)
    base_dir = pwd;
else
    base_dir = fileparts(script_file);
end

% Define the dataset naming pattern and output directory.
dataset_pattern = 'Data_200L_LL250_LH040_noise_*pct_rep_*';

output_root = fullfile(...
    base_dir, ...
    'Parameter_Selection_Validation_OUTPUT');

reset_output_folder = true;

% Define the observed-variable, hidden-regulator, and hidden-global indices.
n_local    = 200;
hidden_idx = 201;
global_idx = 202;
n_total    = 202;

% Set numerical tolerances used for parameter matching and symmetry checks.
parameter_tolerance = 1e-10;
symmetry_tolerance  = 1e-7;

% Define ground-truth and estimated support thresholds.
gt_edge_threshold        = 1e-12;
estimated_edge_threshold = 1e-6;

% Set constants used in the alpha population-selection score.
alpha_tau     = 0.20;
alpha_epsilon = 1e-12;

% Set figure dimensions, resolution, typography, and noise-level colors.
figure_width_in  = 7.01;
figure_height_in = 2.78;
figure_dpi       = 1200;

font_name             = 'Arial';
tick_font_size         = 6.3;
axis_label_font_size   = 7.0;
panel_title_font_size  = 7.3;
legend_font_size       = 6.1;

noise_colors = [...
    0.0000, 0.4470, 0.7410; ...
    0.8500, 0.3250, 0.0980; ...
    0.4660, 0.6740, 0.1880];

if reset_output_folder && exist(output_root, 'dir')
    rmdir(output_root, 's');
end

if ~exist(output_root, 'dir')
    mkdir(output_root);
end


%% Dataset discovery
% Locate dataset folders and extract noise levels and repeat identifiers.
folder_list = dir(fullfile(base_dir, dataset_pattern));
folder_list = folder_list([folder_list.isdir]);

dataset_info = struct(...
    'name', {}, ...
    'path', {}, ...
    'noise_pct', {}, ...
    'repeat_id', {});

for i = 1:numel(folder_list)

    folder_name = folder_list(i).name;

    token = regexp(...
        folder_name, ...
        '^Data_200L_LL250_LH040_noise_(\d+)pct_rep_(\d+)$', ...
        'tokens', ...
        'once');

    if isempty(token)
        continue;
    end

    dataset_info(end + 1).name = folder_name; %#ok<SAGROW>
    dataset_info(end).path = fullfile(base_dir, folder_name);
    dataset_info(end).noise_pct = str2double(token{1});
    dataset_info(end).repeat_id = str2double(token{2});
end

if isempty(dataset_info)
    error([...
        'No matching dataset folders were found beside this .m file.\n' ...
        'Expected folder names such as:\n' ...
        'Data_200L_LL250_LH040_noise_000pct_rep_01\n\n' ...
        'Current folder:\n%s'], ...
        base_dir);
end

sort_key = [...
    [dataset_info.noise_pct].', ...
    [dataset_info.repeat_id].'];

[~, order] = sortrows(sort_key, [1, 2]);
dataset_info = dataset_info(order);

% Print the analysis configuration.
fprintf('============================================================\n');
fprintf('HR-GGM parameter-selection validation\n');
fprintf('Base directory: %s\n', base_dir);
fprintf('Datasets found: %d\n', numel(dataset_info));
fprintf('Output directory: %s\n', output_root);


fprintf('============================================================\n');


%% Dataset analysis
% Initialize containers for per-dataset results and tabular outputs.
analysis_results = struct([]);
lambda_rows = cell(0, 1);
alpha_rows = cell(0, 1);
summary_rows = cell(0, 1);

for d = 1:numel(dataset_info)

    dataset_name = dataset_info(d).name;
    dataset_dir  = dataset_info(d).path;
    noise_pct    = dataset_info(d).noise_pct;
    repeat_id    = dataset_info(d).repeat_id;

    fprintf('\n------------------------------------------------------------\n');
    fprintf('Dataset %d/%d: %s\n', ...
        d, numel(dataset_info), dataset_name);
    fprintf('------------------------------------------------------------\n');

    % Resolve dataset-specific input and result paths.
    data_dir = fullfile(dataset_dir, 'Data');
    build_result_dir = fullfile(dataset_dir, 'build', 'Result');
    alpha_metric_dir = fullfile(build_result_dir, 'Alpha_metric');
    lambda_ratio_dir = fullfile(build_result_dir, 'lambda_ratio');
    scan_result_dir  = fullfile(dataset_dir, 'Result');

    alpha_list_file  = fullfile(data_dir, 'Alpha_list.txt');
    lambda_list_file = fullfile(data_dir, 'Lambda_list.txt');
    theta_gt_file    = fullfile(data_dir, 'Theta_full.txt');
    theta_final_file = fullfile(build_result_dir, 'Theta_final.txt');

    % Verify that all required files and directories are present.
    required_paths = {...
        data_dir, ...
        build_result_dir, ...
        alpha_metric_dir, ...
        lambda_ratio_dir, ...
        scan_result_dir, ...
        alpha_list_file, ...
        lambda_list_file, ...
        theta_gt_file, ...
        theta_final_file};

    for p = 1:numel(required_paths)
        if ~(isfile(required_paths{p}) || isfolder(required_paths{p}))
            error('Required path does not exist:\n%s', required_paths{p});
        end
    end

    % Read parameter grids and precision matrices.
    alpha_list  = read_numeric_vector(alpha_list_file);
    lambda_list = read_numeric_vector(lambda_list_file);

    theta_gt = read_theta_matrix(theta_gt_file, n_total);
    theta_final = read_theta_matrix(theta_final_file, n_total);

    validate_theta_matrix(...
        theta_gt, symmetry_tolerance, ...
        sprintf('%s GT', dataset_name));

    validate_theta_matrix(...
        theta_final, symmetry_tolerance, ...
        sprintf('%s Theta_final', dataset_name));

    % Identify selected alpha and lambda values from the latest score vectors.
    [final_alpha_score_file, final_alpha_loop] = ...
        find_latest_numbered_file(...
        alpha_metric_dir, '^Score_vec_?(\d+)');

    [final_lambda_score_file, final_lambda_loop] = ...
        find_latest_numbered_file(...
        lambda_ratio_dir, '^Score_norm_?(\d+)');

    final_alpha_score = read_score_vector_for_grid(...
        final_alpha_score_file, numel(alpha_list));

    final_lambda_score = read_score_vector_for_grid(...
        final_lambda_score_file, numel(lambda_list));

    selected_alpha_index = finite_argmin(final_alpha_score);
    selected_lambda_index = finite_argmax(final_lambda_score);

    selected_alpha = alpha_list(selected_alpha_index);
    selected_lambda = lambda_list(selected_lambda_index);

    fprintf('Selected alpha:  %.12g (index %d; loop %d)\n', ...
        selected_alpha, selected_alpha_index, final_alpha_loop);

    fprintf('Selected lambda: %.12g (index %d; loop %d)\n', ...
        selected_lambda, selected_lambda_index, final_lambda_loop);

    % Locate one-dimensional full-data parameter scans and verify fixed values.
    [alpha_scan_dir, fixed_lambda_in_folder, gamma_alpha] = ...
        find_unique_scan_folder(...
        scan_result_dir, ...
        'Theta_by_alpha__fixed_lambda_*__gamma_*', ...
        'lambda');

    [lambda_scan_dir, fixed_alpha_in_folder, gamma_lambda] = ...
        find_unique_scan_folder(...
        scan_result_dir, ...
        'Theta_by_lambda__fixed_alpha_*__gamma_*', ...
        'alpha');

    if abs(gamma_alpha - gamma_lambda) > 1e-12
        error('Alpha and lambda scans use different gamma values in %s.', ...
            dataset_name);
    end

    gamma_value = gamma_alpha;

    if abs(fixed_alpha_in_folder - selected_alpha) > ...
            parameter_match_tolerance(...
            selected_alpha, parameter_tolerance)

        error([...
            'The lambda-scan folder does not use the selected alpha.\n' ...
            'Dataset: %s\nSelected alpha: %.12g\nFolder alpha: %.12g'], ...
            dataset_name, selected_alpha, fixed_alpha_in_folder);
    end

    if abs(fixed_lambda_in_folder - selected_lambda) > ...
            parameter_match_tolerance(...
            selected_lambda, parameter_tolerance)

        error([...
            'The alpha-scan folder does not use the selected lambda.\n' ...
            'Dataset: %s\nSelected lambda: %.12g\nFolder lambda: %.12g'], ...
            dataset_name, selected_lambda, fixed_lambda_in_folder);
    end

    % Read all alpha-scan and lambda-scan precision matrices.
    alpha_scan = read_scan_matrices(...
        alpha_scan_dir, ...
        'alpha', ...
        alpha_list, ...
        n_total, ...
        parameter_tolerance, ...
        symmetry_tolerance);

    lambda_scan = read_scan_matrices(...
        lambda_scan_dir, ...
        'lambda', ...
        lambda_list, ...
        n_total, ...
        parameter_tolerance, ...
        symmetry_tolerance);


    % Construct the noise-matched population covariance from the ground truth.
    theta_gt_LL = theta_gt(1:n_local, 1:n_local);

    gt_marginal_precision = marginal_local_precision(...
        theta_gt, ...
        n_local, ...
        [hidden_idx, global_idx]);

    [is_spd, ~] = spd_logdet(gt_marginal_precision);

    if ~is_spd
        error('GT marginal precision is not SPD in %s.', dataset_name);
    end

    gt_local_covariance = ...
        gt_marginal_precision \ eye(n_local);

    gt_local_covariance = ...
        0.5 * (gt_local_covariance + gt_local_covariance.');

    gt_local_sd = sqrt(diag(gt_local_covariance));

    if any(~isfinite(gt_local_sd)) || any(gt_local_sd <= 0)
        error('Invalid GT observed-variable variances in %s.', dataset_name);
    end

    gt_local_correlation = ...
        gt_local_covariance ./ ...
        (gt_local_sd * gt_local_sd.');

    gt_local_correlation = ...
        0.5 * (gt_local_correlation + gt_local_correlation.');

    gt_local_correlation(1:n_local + 1:end) = 1;

    noise_fraction = noise_pct / 100;

    if noise_fraction < 0 || noise_fraction >= 1
        error('Noise fraction must be in [0,1) in %s.', dataset_name);
    end

    population_local_covariance = ...
        (1 - noise_fraction) * gt_local_correlation ...
        + noise_fraction * eye(n_local);

    population_local_covariance = ...
        0.5 * (population_local_covariance + ...
        population_local_covariance.');

    [is_spd, ~] = spd_logdet(population_local_covariance);

    if ~is_spd
        error('Population covariance is not SPD in %s.', dataset_name);
    end


    % Evaluate each lambda candidate using observed-block error and support recovery.
    n_lambda = numel(lambda_scan);

    lambda_values = zeros(n_lambda, 1);
    lambda_error  = nan(n_lambda, 1);
    lambda_precision = nan(n_lambda, 1);
    lambda_recall = nan(n_lambda, 1);
    lambda_f1 = nan(n_lambda, 1);
    lambda_edge_count = nan(n_lambda, 1);

    for i = 1:n_lambda

        theta_hat = lambda_scan(i).theta;
        theta_hat_LL = theta_hat(1:n_local, 1:n_local);

        lambda_values(i) = lambda_scan(i).value;

        lambda_error(i) = relative_frobenius_offdiag(...
            theta_hat_LL, theta_gt_LL);

        [lambda_precision(i), ...
         lambda_recall(i), ...
         lambda_f1(i), ...
         lambda_edge_count(i)] = ...
            native_support_metrics(...
            theta_hat_LL, ...
            theta_gt_LL, ...
            estimated_edge_threshold, ...
            gt_edge_threshold);
    end

    selected_lambda_scan_index = ...
        nearest_parameter_index(lambda_values, selected_lambda);

    truth_best_lambda_index = finite_argmin(lambda_error);
    truth_best_lambda = lambda_values(truth_best_lambda_index);


    % Evaluate each alpha candidate using population loss and global-signal structure.
    n_alpha = numel(alpha_scan);

    alpha_values = zeros(n_alpha, 1);
    alpha_population_loss = nan(n_alpha, 1);
    alpha_entropy = nan(n_alpha, 1);
    alpha_global_magnitude = nan(n_alpha, 1);

    for i = 1:n_alpha

        theta_hat = alpha_scan(i).theta;
        alpha_values(i) = alpha_scan(i).value;

        estimated_marginal_precision = ...
            marginal_local_precision(...
            theta_hat, ...
            n_local, ...
            [hidden_idx, global_idx]);

        alpha_population_loss(i) = ...
            population_negative_loglikelihood(...
            estimated_marginal_precision, ...
            population_local_covariance);

        alpha_entropy(i) = normalized_lg_entropy(...
            theta_hat, ...
            n_local, ...
            global_idx, ...
            alpha_epsilon);

        alpha_global_magnitude(i) = relative_global_magnitude(...
            theta_hat, ...
            n_local, ...
            hidden_idx, ...
            global_idx, ...
            alpha_epsilon);
    end

    valid_magnitude = ...
        alpha_global_magnitude(isfinite(alpha_global_magnitude));

    if isempty(valid_magnitude)
        error('No finite alpha global-magnitude values in %s.', ...
            dataset_name);
    end

    magnitude_reference = max(valid_magnitude);

    if magnitude_reference > alpha_epsilon
        alpha_retention = min(...
            1, ...
            max(...
            0, ...
            alpha_global_magnitude ./ ...
            (alpha_tau * magnitude_reference + alpha_epsilon)));
    else
        alpha_retention = zeros(n_alpha, 1);
    end

    alpha_adjusted_entropy = alpha_entropy .* alpha_retention;

    alpha_population_loss_z = ...
        standardize_finite_vector(alpha_population_loss);

    alpha_adjusted_entropy_z = ...
        standardize_finite_vector(alpha_adjusted_entropy);

    alpha_population_score = ...
        0.5 * alpha_population_loss_z ...
        - 0.5 * alpha_adjusted_entropy_z;

    truth_best_alpha_index = finite_argmin(alpha_population_score);
    truth_best_alpha = alpha_values(truth_best_alpha_index);

    selected_alpha_scan_index = ...
        nearest_parameter_index(alpha_values, selected_alpha);

    alpha_population_score_gap = ...
        alpha_population_score ...
        - alpha_population_score(truth_best_alpha_index);

    cv_population_spearman = ...
        spearman_correlation_no_toolbox(...
        final_alpha_score, ...
        alpha_population_score);


    % Store per-dataset parameter curves, optima, and comparison statistics.
    analysis_results(d).dataset = dataset_name;
    analysis_results(d).noise_pct = noise_pct;
    analysis_results(d).repeat_id = repeat_id;

    analysis_results(d).lambda_values = lambda_values;
    analysis_results(d).lambda_error = lambda_error;
    analysis_results(d).lambda_precision = lambda_precision;
    analysis_results(d).lambda_recall = lambda_recall;
    analysis_results(d).lambda_f1 = lambda_f1;
    analysis_results(d).lambda_edge_count = lambda_edge_count;
    analysis_results(d).selected_lambda = selected_lambda;
    analysis_results(d).selected_lambda_index = ...
        selected_lambda_scan_index;
    analysis_results(d).truth_best_lambda = truth_best_lambda;
    analysis_results(d).truth_best_lambda_index = ...
        truth_best_lambda_index;

    analysis_results(d).alpha_values = alpha_values;
    analysis_results(d).alpha_cv_score = final_alpha_score;
    analysis_results(d).alpha_population_loss = ...
        alpha_population_loss;
    analysis_results(d).alpha_population_score = ...
        alpha_population_score;
    analysis_results(d).alpha_population_score_gap = ...
        alpha_population_score_gap;
    analysis_results(d).selected_alpha = selected_alpha;
    analysis_results(d).selected_alpha_index = ...
        selected_alpha_scan_index;
    analysis_results(d).truth_best_alpha = truth_best_alpha;
    analysis_results(d).truth_best_alpha_index = ...
        truth_best_alpha_index;
    analysis_results(d).cv_population_spearman = ...
        cv_population_spearman;

    % Assemble long-format lambda, alpha, and dataset-summary tables.
    lambda_rows{end + 1, 1} = table(...
        repmat(string(dataset_name), n_lambda, 1), ...
        repmat(noise_pct, n_lambda, 1), ...
        repmat(repeat_id, n_lambda, 1), ...
        lambda_values, ...
        lambda_error, ...
        lambda_precision, ...
        lambda_recall, ...
        lambda_f1, ...
        lambda_edge_count, ...
        (1:n_lambda).' == selected_lambda_scan_index, ...
        (1:n_lambda).' == truth_best_lambda_index, ...
        'VariableNames', {...
            'Dataset', ...
            'NoisePct', ...
            'RepeatID', ...
            'Lambda', ...
            'O_OffDiagonal_RelativeError', ...
            'NativePrecision', ...
            'NativeRecall', ...
            'NativeF1', ...
            'NativeEdgeCount', ...
            'IsSelectedByHRGGM', ...
            'IsTruthBasedOptimum'});

    alpha_rows{end + 1, 1} = table(...
        repmat(string(dataset_name), n_alpha, 1), ...
        repmat(noise_pct, n_alpha, 1), ...
        repmat(repeat_id, n_alpha, 1), ...
        alpha_values, ...
        final_alpha_score(:), ...
        alpha_population_loss, ...
        alpha_population_score, ...
        alpha_population_score_gap, ...
        (1:n_alpha).' == selected_alpha_scan_index, ...
        (1:n_alpha).' == truth_best_alpha_index, ...
        'VariableNames', {...
            'Dataset', ...
            'NoisePct', ...
            'RepeatID', ...
            'Alpha', ...
            'HRGGM_CV_Score', ...
            'PopulationGaussianLoss', ...
            'PopulationSelectionScore', ...
            'PopulationSelectionScoreGap', ...
            'IsSelectedByHRGGM', ...
            'IsTruthBasedOptimum'});

    summary_rows{end + 1, 1} = table(...
        string(dataset_name), ...
        noise_pct, ...
        repeat_id, ...
        gamma_value, ...
        selected_lambda, ...
        truth_best_lambda, ...
        lambda_error(selected_lambda_scan_index), ...
        lambda_error(truth_best_lambda_index), ...
        selected_alpha, ...
        truth_best_alpha, ...
        alpha_population_score_gap(selected_alpha_scan_index), ...
        alpha_population_loss(selected_alpha_scan_index), ...
        alpha_population_loss(truth_best_alpha_index), ...
        cv_population_spearman, ...
        'VariableNames', {...
            'Dataset', ...
            'NoisePct', ...
            'RepeatID', ...
            'Gamma', ...
            'SelectedLambda', ...
            'TruthBasedLambda', ...
            'SelectedLambda_O_Error', ...
            'TruthBasedLambda_O_Error', ...
            'SelectedAlpha', ...
            'TruthBasedAlpha', ...
            'SelectedAlpha_PopulationScoreGap', ...
            'SelectedAlpha_PopulationGaussianLoss', ...
            'TruthBasedAlpha_PopulationGaussianLoss', ...
            'CV_PopulationScore_Spearman'});
end

%% Numerical outputs
% Concatenate per-dataset tables and write CSV and MAT outputs.
lambda_scan_table = vertcat(lambda_rows{:});
alpha_scan_table = vertcat(alpha_rows{:});
dataset_summary = vertcat(summary_rows{:});


writetable(...
    lambda_scan_table, ...
    fullfile(output_root, 'Lambda_scan_results.csv'));

writetable(...
    alpha_scan_table, ...
    fullfile(output_root, 'Alpha_scan_results.csv'));

writetable(...
    dataset_summary, ...
    fullfile(output_root, 'Parameter_selection_summary.csv'));

save(...
    fullfile(output_root, 'Parameter_selection_results.mat'), ...
    'analysis_results', ...
    'lambda_scan_table', ...
    'alpha_scan_table', ...
    'dataset_summary');


%% Figure generation
% Generate the three-panel main figure and the alpha-score supplement.
main_png_file = fullfile(...
    output_root, ...
    'Figure_Main_ParameterSelection_1x3.png');

main_pdf_file = fullfile(...
    output_root, ...
    'Figure_Main_ParameterSelection_1x3.pdf');

main_fig_file = fullfile(...
    output_root, ...
    'Figure_Main_ParameterSelection_1x3.fig');

make_main_figure(...
    analysis_results, ...
    noise_colors, ...
    main_png_file, ...
    main_pdf_file, ...
    main_fig_file, ...
    figure_width_in, ...
    figure_height_in, ...
    figure_dpi, ...
    font_name, ...
    tick_font_size, ...
    axis_label_font_size, ...
    panel_title_font_size, ...
    legend_font_size);

supp_png_file = fullfile(...
    output_root, ...
    'Figure_Supplement_Alpha_CV_vs_Population_3x3.png');

supp_pdf_file = fullfile(...
    output_root, ...
    'Figure_Supplement_Alpha_CV_vs_Population_3x3.pdf');

make_alpha_supplement_figure(...
    analysis_results, ...
    noise_colors, ...
    supp_png_file, ...
    supp_pdf_file, ...
    7.01, ...
    7.01, ...
    figure_dpi, ...
    font_name, ...
    tick_font_size, ...
    axis_label_font_size, ...
    panel_title_font_size);

fprintf('\n============================================================\n');
fprintf('Analysis completed successfully.\n');
fprintf('Output folder:\n%s\n', output_root);
fprintf('Main figure:\n%s\n', main_png_file);
fprintf('Supplementary figure:\n%s\n', supp_png_file);

% Report completion and generated output files.
fprintf('============================================================\n');


%% Helper functions
% Reads a finite numeric parameter vector from a supported text layout.
function x = read_numeric_vector(filename)

    A = readmatrix(filename);
    A = remove_nan_border(A);

    if isempty(A)
        error('Empty numeric file:\n%s', filename);
    end

    if isvector(A)
        x = A(:);
    elseif size(A, 2) == 2
        x = A(:, end);
    elseif size(A, 1) == 2
        x = A(end, :).';
    else
        error('Expected a numeric vector in:\n%s', filename);
    end

    x = x(isfinite(x));
end

% Reads and validates a score vector against a parameter-grid length.
function score = read_score_vector_for_grid(filename, expected_length)

    A = readmatrix(filename);
    A = remove_nan_border(A);

    if isempty(A)
        error('Empty score file:\n%s', filename);
    end

    if isvector(A)
        score = A(:);
    elseif size(A, 1) == expected_length
        score = A(:, end);
    elseif size(A, 2) == expected_length
        score = A(end, :).';
    else
        error([...
            'Cannot map score file of size %d x %d to a grid of ' ...
            'length %d:\n%s'], ...
            size(A, 1), size(A, 2), expected_length, filename);
    end

    score = score(:);

    if numel(score) ~= expected_length
        error('Score length does not match the parameter grid:\n%s', ...
            filename);
    end

    if any(~isfinite(score))
        error('Score curve contains NaN or Inf:\n%s', filename);
    end
end

% Reads, validates, and symmetrizes a square precision matrix.
function theta = read_theta_matrix(filename, expected_size)

    theta = readmatrix(filename);
    theta = remove_nan_border(theta);

    if ~isequal(size(theta), [expected_size, expected_size])
        error([...
            'Theta size is %d x %d; expected %d x %d:\n%s'], ...
            size(theta, 1), ...
            size(theta, 2), ...
            expected_size, ...
            expected_size, ...
            filename);
    end

    if any(~isfinite(theta), 'all')
        error('Theta contains NaN or Inf:\n%s', filename);
    end

    theta = 0.5 * (theta + theta.');
end

% Removes rows and columns that contain only NaN values.
function A = remove_nan_border(A)

    if isempty(A)
        return;
    end

    A = A(~all(isnan(A), 2), :);
    A = A(:, ~all(isnan(A), 1));
end

% Reports relative matrix asymmetry when it exceeds the specified tolerance.
function validate_theta_matrix(theta, symmetry_tolerance, label)

    relative_asymmetry = ...
        norm(theta - theta.', 'fro') / ...
        max(norm(theta, 'fro'), eps);

    if relative_asymmetry > symmetry_tolerance
        warning('%s relative asymmetry is %.3e.', ...
            label, relative_asymmetry);
    end
end

% Selects the numbered score file with the largest parsed identifier.
function [selected_file, largest_id] = ...
    find_latest_numbered_file(folder, regular_expression)

    files = dir(fullfile(folder, '*'));
    files = files(~[files.isdir]);

    ids = nan(numel(files), 1);

    for i = 1:numel(files)

        token = regexp(...
            files(i).name, ...
            regular_expression, ...
            'tokens', ...
            'once');

        if ~isempty(token)
            ids(i) = str2double(token{1});
        end
    end

    valid = isfinite(ids);

    if ~any(valid)
        error([...
            'No numbered score file matching "%s" was found in:\n%s'], ...
            regular_expression, folder);
    end

    files = files(valid);
    ids = ids(valid);

    [largest_id, index] = max(ids);

    selected_file = fullfile(...
        files(index).folder, ...
        files(index).name);
end

% Locates a unique scan folder and parses its fixed parameter and gamma values.
function [folder_path, fixed_value, gamma_value] = ...
    find_unique_scan_folder(result_root, wildcard_pattern, fixed_name)

    folders = dir(fullfile(result_root, wildcard_pattern));
    folders = folders([folders.isdir]);

    if numel(folders) ~= 1
        error([...
            'Expected exactly one scan folder matching:\n%s\n' ...
            'Found %d under:\n%s'], ...
            wildcard_pattern, numel(folders), result_root);
    end

    folder_name = folders(1).name;

    if strcmpi(fixed_name, 'lambda')
        expression = ...
            '^Theta_by_alpha__fixed_lambda_(.+)__gamma_(.+)$';
    elseif strcmpi(fixed_name, 'alpha')
        expression = ...
            '^Theta_by_lambda__fixed_alpha_(.+)__gamma_(.+)$';
    else
        error('Unknown fixed parameter name: %s', fixed_name);
    end

    token = regexp(folder_name, expression, 'tokens', 'once');

    if isempty(token)
        error('Cannot parse scan-folder parameters:\n%s', folder_name);
    end

    fixed_value = decode_parameter_token(token{1});
    gamma_value = decode_parameter_token(token{2});

    folder_path = fullfile(result_root, folder_name);
end

% Converts filename-safe parameter tokens to numeric values.
function value = decode_parameter_token(token)

    token = strtrim(char(token));

    is_negative = startsWith(token, 'm');

    if is_negative
        token = token(2:end);
    end

    token = strrep(token, 'p', '.');

    value = str2double(token);

    if ~isfinite(value)
        error('Cannot decode numeric parameter token: %s', token);
    end

    if is_negative
        value = -value;
    end
end

% Computes a scale-aware tolerance for parameter comparisons.
function tolerance = parameter_match_tolerance(value, base_tolerance)

    tolerance = max(...
        base_tolerance, ...
        base_tolerance * max(1, abs(value)));
end

% Reads an indexed parameter scan and validates file ordering and matrix dimensions.
function scan = read_scan_matrices(...
    folder, ...
    parameter_name, ...
    parameter_list, ...
    expected_theta_size, ...
    parameter_tolerance, ...
    symmetry_tolerance)

    files = dir(fullfile(...
        folder, ...
        sprintf('Theta_%s_*', lower(parameter_name))));

    files = files(~[files.isdir]);

    indices = nan(numel(files), 1);
    values_from_filename = nan(numel(files), 1);

    for i = 1:numel(files)

        [~, stem, ~] = fileparts(files(i).name);

        expression = sprintf(...
            '^Theta_%s_(\\d+)__value_(.+)$', ...
            lower(parameter_name));

        token = regexp(stem, expression, 'tokens', 'once');

        if isempty(token)
            continue;
        end

        indices(i) = str2double(token{1});
        values_from_filename(i) = ...
            decode_parameter_token(token{2});
    end

    valid = isfinite(indices);

    files = files(valid);
    indices = indices(valid);
    values_from_filename = values_from_filename(valid);

    if isempty(files)
        error('No parseable scan matrices were found in:\n%s', folder);
    end

    [indices, order] = sort(indices);

    files = files(order);
    values_from_filename = values_from_filename(order);

    expected_indices = (1:numel(parameter_list)).';

    if numel(indices) ~= numel(expected_indices) || ...
            any(indices(:) ~= expected_indices)

        error('Scan files are incomplete or misindexed in:\n%s', folder);
    end

    scan = struct(...
        'index', cell(numel(files), 1), ...
        'value', cell(numel(files), 1), ...
        'theta', cell(numel(files), 1), ...
        'file', cell(numel(files), 1));

    for i = 1:numel(files)

        expected_value = parameter_list(i);

        if isfinite(values_from_filename(i))

            allowed_difference = parameter_match_tolerance(...
                expected_value, parameter_tolerance);

            if abs(values_from_filename(i) - expected_value) > ...
                    allowed_difference

                warning([...
                    'Filename value %.12g does not match list value ' ...
                    '%.12g at index %d in:\n%s'], ...
                    values_from_filename(i), ...
                    expected_value, ...
                    i, ...
                    folder);
            end
        end

        theta_file = fullfile(files(i).folder, files(i).name);

        theta = read_theta_matrix(...
            theta_file, expected_theta_size);

        validate_theta_matrix(...
            theta, symmetry_tolerance, theta_file);

        scan(i).index = i;
        scan(i).value = expected_value;
        scan(i).theta = theta;
        scan(i).file = theta_file;
    end
end

% Returns the grid index nearest to a target parameter value.
function index = nearest_parameter_index(values, target)

    [~, index] = min(abs(values(:) - target));
end

% Returns the index of the minimum finite value.
function index = finite_argmin(values)

    values = values(:);
    valid = isfinite(values);

    if ~any(valid)
        error('No finite value is available for minimization.');
    end

    valid_indices = find(valid);
    [~, local_index] = min(values(valid));
    index = valid_indices(local_index);
end

% Returns the index of the maximum finite value.
function index = finite_argmax(values)

    values = values(:);
    valid = isfinite(values);

    if ~any(valid)
        error('No finite value is available for maximization.');
    end

    valid_indices = find(valid);
    [~, local_index] = max(values(valid));
    index = valid_indices(local_index);
end

% Computes observed-variable marginal precision by removing H and G via a Schur complement.
function marginal_precision = marginal_local_precision(...
    theta, n_local, nuisance_indices)

    theta_LL = theta(1:n_local, 1:n_local);
    theta_LZ = theta(1:n_local, nuisance_indices);
    theta_ZL = theta(nuisance_indices, 1:n_local);
    theta_ZZ = theta(nuisance_indices, nuisance_indices);

    if rcond(theta_ZZ) < 1e-12
        marginal_precision = nan(n_local);
        return;
    end

    marginal_precision = ...
        theta_LL - theta_LZ * (theta_ZZ \ theta_ZL);

    marginal_precision = ...
        0.5 * (marginal_precision + marginal_precision.');
end

% Computes the population Gaussian loss: tr(Sigma_pop K) - logdet(K).
function loss = population_negative_loglikelihood(...
    precision_matrix, population_covariance)

    precision_matrix = ...
        0.5 * (precision_matrix + precision_matrix.');

    [is_spd, logdet_value] = spd_logdet(precision_matrix);

    if ~is_spd
        loss = NaN;
        return;
    end

    loss = trace(population_covariance * precision_matrix) ...
        - logdet_value;

    if ~isfinite(loss)
        loss = NaN;
    end
end

% Tests positive definiteness and computes the log determinant by Cholesky factorization.
function [is_spd, logdet_value] = spd_logdet(A)

    A = 0.5 * (A + A.');

    [R, flag] = chol(A);

    is_spd = flag == 0;

    if is_spd
        logdet_value = 2 * sum(log(diag(R)));
    else
        logdet_value = NaN;
    end
end

% Computes normalized entropy from all absolute entries of the global-induced matrix.
function entropy_value = normalized_lg_entropy(...
    theta, n_local, global_idx, epsilon_value)

    global_matrix = global_induced_matrix(...
        theta, n_local, global_idx);

    weights = abs(global_matrix(:));
    weights = weights(isfinite(weights));

    total_weight = sum(weights);

    if isempty(weights) || total_weight <= epsilon_value
        entropy_value = 0;
        return;
    end

    probabilities = weights / total_weight;
    probabilities = probabilities(probabilities > 0);

    raw_entropy = -sum(probabilities .* log(probabilities));

    denominator = log(numel(weights));

    if denominator <= 0
        entropy_value = 0;
    else
        entropy_value = raw_entropy / denominator;
    end
end

% Computes the observed-space matrix induced by the hidden global variable.
function global_matrix = global_induced_matrix(...
    theta, n_local, global_idx)

    theta_LG = theta(1:n_local, global_idx);
    theta_GL = theta(global_idx, 1:n_local);
    theta_GG = theta(global_idx, global_idx);

    if ~isfinite(theta_GG) || abs(theta_GG) <= eps
        global_matrix = nan(n_local);
        return;
    end

    global_matrix = ...
        theta_LG * (1 / theta_GG) * theta_GL;

    global_matrix = ...
        0.5 * (global_matrix + global_matrix.');
end

% Computes global-effect magnitude relative to observed-variable marginal precision.
function magnitude = relative_global_magnitude(...
    theta, ...
    n_local, ...
    hidden_idx, ...
    global_idx, ...
    epsilon_value)

    marginal_precision = marginal_local_precision(...
        theta, ...
        n_local, ...
        [hidden_idx, global_idx]);

    global_matrix = global_induced_matrix(...
        theta, ...
        n_local, ...
        global_idx);

    numerator = norm(global_matrix, 'fro');
    denominator = norm(marginal_precision, 'fro') + epsilon_value;

    magnitude = numerator / denominator;

    if ~isfinite(magnitude)
        magnitude = NaN;
    end
end

% Standardizes finite entries while preserving non-finite positions.
function z = standardize_finite_vector(x)

    x = x(:);
    z = nan(size(x));

    valid = isfinite(x);

    if ~any(valid)
        return;
    end

    current = x(valid);
    current_mean = mean(current);
    current_sd = std(current, 0);

    if current_sd <= eps
        z(valid) = 0;
    else
        z(valid) = (current - current_mean) / current_sd;
    end
end

% Computes relative Frobenius error over off-diagonal matrix entries.
function error_value = relative_frobenius_offdiag(A, B)

    A = 0.5 * (A + A.');
    B = 0.5 * (B + B.');

    n = size(A, 1);
    mask = ~eye(n);

    numerator = norm(A(mask) - B(mask), 2);
    denominator = norm(B(mask), 2);

    if denominator <= eps
        error_value = NaN;
    else
        error_value = numerator / denominator;
    end
end

% Computes undirected support precision, recall, F1, and predicted edge count.
function [precision_value, recall_value, f1_value, edge_count] = ...
    native_support_metrics(...
    estimated_LL, ...
    truth_LL, ...
    estimated_threshold, ...
    truth_threshold)

    estimated_LL = 0.5 * (estimated_LL + estimated_LL.');
    truth_LL = 0.5 * (truth_LL + truth_LL.');

    n = size(estimated_LL, 1);
    mask = triu(true(n), 1);

    predicted = abs(estimated_LL(mask)) > estimated_threshold;
    truth = abs(truth_LL(mask)) > truth_threshold;

    TP = sum(predicted & truth);
    FP = sum(predicted & ~truth);
    FN = sum(~predicted & truth);

    edge_count = sum(predicted);

    if TP + FP > 0
        precision_value = TP / (TP + FP);
    else
        precision_value = 0;
    end

    if TP + FN > 0
        recall_value = TP / (TP + FN);
    else
        recall_value = 0;
    end

    if precision_value + recall_value > 0
        f1_value = ...
            2 * precision_value * recall_value / ...
            (precision_value + recall_value);
    else
        f1_value = 0;
    end
end

% Computes Spearman correlation using internally calculated average tied ranks.
function rho = spearman_correlation_no_toolbox(x, y)

    x = x(:);
    y = y(:);

    valid = isfinite(x) & isfinite(y);
    x = x(valid);
    y = y(valid);

    if numel(x) < 2
        rho = NaN;
        return;
    end

    rank_x = average_tied_ranks(x);
    rank_y = average_tied_ranks(y);

    if std(rank_x, 0) <= eps || std(rank_y, 0) <= eps
        rho = NaN;
        return;
    end

    C = corrcoef(rank_x, rank_y);
    rho = C(1, 2);
end

% Assigns average ranks to tied values.
function ranks = average_tied_ranks(x)

    x = x(:);

    [sorted_x, order] = sort(x, 'ascend');
    ranks_sorted = zeros(size(sorted_x));

    i = 1;

    while i <= numel(sorted_x)

        j = i;

        while j < numel(sorted_x) && ...
                sorted_x(j + 1) == sorted_x(i)
            j = j + 1;
        end

        ranks_sorted(i:j) = (i + j) / 2;
        i = j + 1;
    end

    ranks = zeros(size(x));
    ranks(order) = ranks_sorted;
end

% Creates and exports the three-panel parameter-selection figure.
function make_main_figure(...
    results, ...
    noise_colors, ...
    png_file, ...
    pdf_file, ...
    fig_file, ...
    width_in, ...
    height_in, ...
    dpi, ...
    font_name, ...
    tick_font_size, ...
    axis_label_font_size, ...
    panel_title_font_size, ...
    legend_font_size)

    noise_levels = sort(unique([results.noise_pct]));

    fig = figure(...
        'Visible', 'off', ...
        'Color', 'w', ...
        'Units', 'inches', ...
        'Position', [1, 1, width_in, height_in], ...
        'PaperUnits', 'inches', ...
        'PaperPosition', [0, 0, width_in, height_in], ...
        'PaperSize', [width_in, height_in], ...
        'Renderer', 'painters', ...
        'GraphicsSmoothing', 'on');

    layout = tiledlayout(...
        fig, ...
        1, 3, ...
        'TileSpacing', 'compact', ...
        'Padding', 'compact');

    axA = nexttile(layout, 1);
    plot_lambda_panel(...
        axA, results, noise_levels, noise_colors);

    axB = nexttile(layout, 2);
    plot_alpha_panel(...
        axB, results, noise_levels, noise_colors);

    axC = nexttile(layout, 3);
    plot_population_KL_panel(...
        axC, results, noise_levels, noise_colors);

    shared_handles = gobjects(5, 1);

    hold(axA, 'on');

    for n = 1:numel(noise_levels)
        shared_handles(n) = plot(...
            axA, NaN, NaN, '-', ...
            'Color', noise_colors(n, :), ...
            'LineWidth', 1.55);
    end

    shared_handles(4) = scatter(...
        axA, NaN, NaN, 42, ...
        'Marker', 'o', ...
        'MarkerFaceColor', 'w', ...
        'MarkerEdgeColor', [0.30, 0.30, 0.30], ...
        'LineWidth', 1.15);

    shared_handles(5) = scatter(...
        axA, NaN, NaN, 42, ...
        'Marker', 'p', ...
        'MarkerFaceColor', [0.35, 0.35, 0.35], ...
        'MarkerEdgeColor', 'k', ...
        'LineWidth', 0.80);

    shared_labels = [...
        arrayfun(@(x) sprintf('%d%% noise', x), ...
        noise_levels, 'UniformOutput', false), ...
        {'GT-based optimum', 'Selected by HR-GGM'}];

    shared_legend = legend(...
        axA, ...
        shared_handles, ...
        shared_labels, ...
        'Orientation', 'horizontal', ...
        'NumColumns', 5, ...
        'Box', 'off', ...
        'FontName', font_name, ...
        'FontSize', legend_font_size);

    shared_legend.Layout.Tile = 'south';

    axes_list = [axA, axB, axC];

    for i = 1:numel(axes_list)

        ax = axes_list(i);
        ax.FontName = font_name;
        ax.FontSize = tick_font_size;
        ax.LineWidth = 0.7;
        ax.TickDir = 'out';
        ax.Layer = 'top';
        ax.Box = 'off';
        ax.GridAlpha = 0.18;

        ax.XLabel.FontName = font_name;
        ax.XLabel.FontSize = axis_label_font_size;

        ax.YLabel.FontName = font_name;
        ax.YLabel.FontSize = axis_label_font_size;

        ax.Title.FontName = font_name;
        ax.Title.FontSize = panel_title_font_size;
        ax.Title.FontWeight = 'bold';
    end

    drawnow;

    exportgraphics(...
        fig, png_file, ...
        'Resolution', dpi, ...
        'BackgroundColor', 'white');

    exportgraphics(...
        fig, pdf_file, ...
        'ContentType', 'vector', ...
        'BackgroundColor', 'white');

    savefig(fig, fig_file);
    close(fig);
end

% Plots lambda-dependent observed-block error and selected parameter markers.
function plot_lambda_panel(...
    ax, results, noise_levels, noise_colors)

    hold(ax, 'on');

    for n = 1:numel(noise_levels)

        current_noise = noise_levels(n);
        subset = results([results.noise_pct] == current_noise);

        [~, order] = sort([subset.repeat_id]);
        subset = subset(order);

        common_x = subset(1).lambda_values(:);
        Y = nan(numel(common_x), numel(subset));

        for r = 1:numel(subset)

            x = subset(r).lambda_values(:);
            y = subset(r).lambda_error(:);

            if numel(x) ~= numel(common_x) || ...
                    any(abs(x - common_x) > 1e-12)
                error('Lambda grids differ within noise level %d%%.', ...
                    current_noise);
            end

            Y(:, r) = y;

            plot(...
                ax, x, y, '-', ...
                'Color', lighten_color(noise_colors(n, :), 0.68), ...
                'LineWidth', 0.65, ...
                'HandleVisibility', 'off');

            scatter(...
                ax, ...
                x(subset(r).truth_best_lambda_index), ...
                y(subset(r).truth_best_lambda_index), ...
                52, ...
                'Marker', 'o', ...
                'MarkerFaceColor', 'w', ...
                'MarkerEdgeColor', noise_colors(n, :), ...
                'LineWidth', 1.25, ...
                'HandleVisibility', 'off');

            scatter(...
                ax, ...
                x(subset(r).selected_lambda_index), ...
                y(subset(r).selected_lambda_index), ...
                60, ...
                'Marker', 'p', ...
                'MarkerFaceColor', noise_colors(n, :), ...
                'MarkerEdgeColor', 'k', ...
                'LineWidth', 0.75, ...
                'HandleVisibility', 'off');
        end

        plot(...
            ax, ...
            common_x, ...
            mean(Y, 2, 'omitnan'), ...
            '-', ...
            'Color', noise_colors(n, :), ...
            'LineWidth', 1.60, ...
            'HandleVisibility', 'off');
    end

    set(ax, 'XScale', 'log');

    xlabel(ax, '\lambda', 'Interpreter', 'tex');
    ylabel(ax, 'Observed off-diagonal relative error');

    title(ax, '(A) \lambda selection', ...
        'Interpreter', 'tex');

    grid(ax, 'on');
end

% Plots alpha population-score gaps and selected parameter markers.
function plot_alpha_panel(...
    ax, results, noise_levels, noise_colors)

    hold(ax, 'on');

    for n = 1:numel(noise_levels)

        current_noise = noise_levels(n);
        subset = results([results.noise_pct] == current_noise);

        [~, order] = sort([subset.repeat_id]);
        subset = subset(order);

        common_x = subset(1).alpha_values(:);
        Y = nan(numel(common_x), numel(subset));

        for r = 1:numel(subset)

            x = subset(r).alpha_values(:);
            y = subset(r).alpha_population_score_gap(:);

            if numel(x) ~= numel(common_x) || ...
                    any(abs(x - common_x) > 1e-12)
                error('Alpha grids differ within noise level %d%%.', ...
                    current_noise);
            end

            Y(:, r) = y;

            plot(...
                ax, x, y, '-', ...
                'Color', lighten_color(noise_colors(n, :), 0.68), ...
                'LineWidth', 0.65, ...
                'HandleVisibility', 'off');

            scatter(...
                ax, ...
                x(subset(r).truth_best_alpha_index), ...
                y(subset(r).truth_best_alpha_index), ...
                52, ...
                'Marker', 'o', ...
                'MarkerFaceColor', 'w', ...
                'MarkerEdgeColor', noise_colors(n, :), ...
                'LineWidth', 1.25, ...
                'HandleVisibility', 'off');

            scatter(...
                ax, ...
                x(subset(r).selected_alpha_index), ...
                y(subset(r).selected_alpha_index), ...
                60, ...
                'Marker', 'p', ...
                'MarkerFaceColor', noise_colors(n, :), ...
                'MarkerEdgeColor', 'k', ...
                'LineWidth', 0.75, ...
                'HandleVisibility', 'off');
        end

        plot(...
            ax, ...
            common_x, ...
            mean(Y, 2, 'omitnan'), ...
            '-', ...
            'Color', noise_colors(n, :), ...
            'LineWidth', 1.60, ...
            'HandleVisibility', 'off');
    end

    yline(...
        ax, 0, '--', ...
        'Color', [0.40, 0.40, 0.40], ...
        'LineWidth', 0.8, ...
        'HandleVisibility', 'off');

    set(ax, 'XScale', 'log');

    xlabel(ax, '\alpha', 'Interpreter', 'tex');
    ylabel(ax, 'Selection score gap');

    title(ax, '(B) \alpha selection', ...
        'Interpreter', 'tex');

    grid(ax, 'on');
end

% Compares population Gaussian loss at reference and HR-GGM-selected alpha values.
% The reference minimizes the combined population score, not the loss alone.
function plot_population_KL_panel(...
    ax, results, noise_levels, noise_colors)

    hold(ax, 'on');

    all_values = [];

    best_offset = -0.13;
    selected_offset = 0.13;

    for n = 1:numel(noise_levels)

        current_noise = noise_levels(n);
        subset = results([results.noise_pct] == current_noise);

        [~, order] = sort([subset.repeat_id]);
        subset = subset(order);

        best_values = nan(numel(subset), 1);
        selected_values = nan(numel(subset), 1);

        for r = 1:numel(subset)

            best_values(r) = ...
                subset(r).alpha_population_loss(...
                subset(r).truth_best_alpha_index);

            selected_values(r) = ...
                subset(r).alpha_population_loss(...
                subset(r).selected_alpha_index);
        end

        all_values = [all_values; best_values; selected_values]; %#ok<AGROW>

        if numel(subset) == 1
            jitter = 0;
        else
            jitter = linspace(-0.035, 0.035, numel(subset)).';
        end

        for r = 1:numel(subset)

            scatter(...
                ax, ...
                n + best_offset + jitter(r), ...
                best_values(r), ...
                40, ...
                'Marker', 'o', ...
                'MarkerFaceColor', 'w', ...
                'MarkerEdgeColor', noise_colors(n, :), ...
                'LineWidth', 1.10, ...
                'HandleVisibility', 'off');

            scatter(...
                ax, ...
                n + selected_offset + jitter(r), ...
                selected_values(r), ...
                46, ...
                'Marker', 'p', ...
                'MarkerFaceColor', noise_colors(n, :), ...
                'MarkerEdgeColor', 'k', ...
                'LineWidth', 0.70, ...
                'HandleVisibility', 'off');
        end

        best_mean = mean(best_values, 'omitnan');
        best_sd = std(best_values, 0, 'omitnan');

        selected_mean = mean(selected_values, 'omitnan');
        selected_sd = std(selected_values, 0, 'omitnan');

        errorbar(...
            ax, ...
            n + best_offset, ...
            best_mean, ...
            best_sd, ...
            'Color', noise_colors(n, :), ...
            'LineStyle', 'none', ...
            'LineWidth', 1.0, ...
            'CapSize', 3, ...
            'HandleVisibility', 'off');

        errorbar(...
            ax, ...
            n + selected_offset, ...
            selected_mean, ...
            selected_sd, ...
            'Color', noise_colors(n, :), ...
            'LineStyle', 'none', ...
            'LineWidth', 1.0, ...
            'CapSize', 3, ...
            'HandleVisibility', 'off');

        scatter(...
            ax, ...
            n + best_offset, ...
            best_mean, ...
            70, ...
            'Marker', 'o', ...
            'MarkerFaceColor', 'w', ...
            'MarkerEdgeColor', noise_colors(n, :), ...
            'LineWidth', 1.45, ...
            'HandleVisibility', 'off');

        scatter(...
            ax, ...
            n + selected_offset, ...
            selected_mean, ...
            78, ...
            'Marker', 'p', ...
            'MarkerFaceColor', noise_colors(n, :), ...
            'MarkerEdgeColor', 'k', ...
            'LineWidth', 0.85, ...
            'HandleVisibility', 'off');
    end

    xlim(ax, [0.55, numel(noise_levels) + 0.45]);

    xticks(ax, 1:numel(noise_levels));

    xticklabels(...
        ax, ...
        arrayfun(...
        @(x) sprintf('%d%%', x), ...
        noise_levels, ...
        'UniformOutput', false));

    xlabel(ax, 'Noise variance fraction');
    ylabel(ax, 'Population Gaussian loss');

    title(ax, '(C) Population Gaussian loss', ...
        'Interpreter', 'tex');

    valid_values = all_values(isfinite(all_values));

    if isempty(valid_values)
        ylim(ax, [0, 1]);
    else
        low = min(valid_values);
        high = max(valid_values);
        span = high - low;

        if span <= eps
            span = max(abs(high), 1) * 0.1;
        end

        ylim(ax, [...
            max(0, low - 0.10 * span), ...
            high + 0.15 * span]);
    end

    grid(ax, 'on');
end

% Creates and exports per-dataset alpha score-comparison panels.
function make_alpha_supplement_figure(...
    results, ...
    noise_colors, ...
    png_file, ...
    pdf_file, ...
    width_in, ...
    height_in, ...
    dpi, ...
    font_name, ...
    tick_font_size, ...
    axis_label_font_size, ...
    panel_title_font_size)

    sort_key = [[results.noise_pct].', [results.repeat_id].'];
    [~, order] = sortrows(sort_key, [1, 2]);
    results = results(order);

    noise_levels = sort(unique([results.noise_pct]));

    fig = figure(...
        'Visible', 'off', ...
        'Color', 'w', ...
        'Units', 'inches', ...
        'Position', [1, 1, width_in, height_in], ...
        'Renderer', 'painters');

    layout = tiledlayout(...
        fig, 3, 3, ...
        'TileSpacing', 'compact', ...
        'Padding', 'compact');

    for i = 1:numel(results)

        ax = nexttile(layout, i);
        hold(ax, 'on');

        noise_index = find(...
            noise_levels == results(i).noise_pct, ...
            1, 'first');

        current_color = noise_colors(noise_index, :);

        x = results(i).alpha_values(:);

        cv_score = standardize_finite_vector(...
            results(i).alpha_cv_score(:));

        population_score = standardize_finite_vector(...
            results(i).alpha_population_score(:));

        plot(...
            ax, x, cv_score, '-', ...
            'Color', [0.25, 0.25, 0.25], ...
            'LineWidth', 1.0, ...
            'DisplayName', 'HR-GGM CV score');

        plot(...
            ax, x, population_score, '-', ...
            'Color', current_color, ...
            'LineWidth', 1.2, ...
            'DisplayName', 'Population score');

        scatter(...
            ax, ...
            x(results(i).selected_alpha_index), ...
            cv_score(results(i).selected_alpha_index), ...
            30, ...
            'Marker', 'p', ...
            'MarkerFaceColor', current_color, ...
            'MarkerEdgeColor', 'k', ...
            'LineWidth', 0.6, ...
            'HandleVisibility', 'off');

        set(ax, 'XScale', 'log');

        xlabel(ax, '\alpha', ...
            'Interpreter', 'tex', ...
            'FontSize', axis_label_font_size);

        ylabel(ax, 'Standardized score', ...
            'FontSize', axis_label_font_size);

        title(...
            ax, ...
            sprintf('%d%% noise, repeat %d', ...
            results(i).noise_pct, results(i).repeat_id), ...
            'FontWeight', 'bold', ...
            'FontSize', panel_title_font_size);

        ax.FontName = font_name;
        ax.FontSize = tick_font_size;
        ax.LineWidth = 0.7;
        ax.TickDir = 'out';
        ax.Layer = 'top';
        ax.Box = 'off';
        ax.GridAlpha = 0.18;

        grid(ax, 'on');

        if i == 1
            legend(ax, ...
                'Location', 'best', ...
                'Box', 'off', ...
                'FontSize', tick_font_size);
        end
    end

    exportgraphics(...
        fig, png_file, ...
        'Resolution', dpi, ...
        'BackgroundColor', 'white');

    exportgraphics(...
        fig, pdf_file, ...
        'ContentType', 'vector', ...
        'BackgroundColor', 'white');

    close(fig);
end

% Blends an RGB color toward white by the specified amount.
function color_out = lighten_color(color_in, amount)

    amount = max(0, min(1, amount));
    color_out = color_in + amount * (1 - color_in);
end

