%% ========================================================================
% Simulation data generator for a 500-local, 5-hidden, 1-global network.
%
% Network structure:
%   500 local nodes arranged in 100 groups of five
%   5 hidden nodes and 1 global node
%   200 within-group LL edges and 400 between-group LL edges
%   75 H1-connected local nodes: 30 prior and 45 held-out nodes
%   28 non-H1 local nodes with elevated global loadings
%
% The script constructs candidate precision matrices, validates the selected
% structure, generates standardized observations, and writes the model input
% files and ground-truth precision matrix for each repeat.
%
% Each Data folder contains:
%   Alpha_list.txt, Data_whole.bin, Idx_g_list.txt,
%   Idx_h_list.txt, Lambda_list.txt, and Theta_full.txt.
%% ========================================================================

clear;
clc;
close all force;
echo off;
diary off;
warning_state = warning;
warning_cleanup = onCleanup(@() warning(warning_state)); %#ok<NASGU>
warning('off', 'all');

%% =========================== Output settings =============================

script_file = mfilename('fullpath');

if isempty(script_file)
    input_folder = pwd;
else
    input_folder = fileparts(script_file);
end

Alpha_list_file = fullfile(input_folder, 'Alpha_list.txt');
Lambda_list_file = fullfile(input_folder, 'Lambda_list.txt');

if ~isfile(Alpha_list_file)
    error('Required input file does not exist: %s', Alpha_list_file);
end

if ~isfile(Lambda_list_file)
    error('Required input file does not exist: %s', Lambda_list_file);
end

RootOutputFolder = fullfile( ...
    pwd, ...
    'Sim_500L_5H_globalDominant_25pct');

reset_output_folder = true;
require_essential_gate_before_writing = true;

if reset_output_folder && exist(RootOutputFolder, 'dir')
    rmdir(RootOutputFolder, 's');
end

if ~exist(RootOutputFolder, 'dir')
    mkdir(RootOutputFolder);
end

%% ========================= Network dimensions ============================

n_nodes_per_group = 5;
n_groups = 100;
n_local = n_nodes_per_group * n_groups;  % 500

n_hidden = 5;
n_global = 1;

n_samples = 10000;
n_repeats = 3;

p = n_local + n_hidden + n_global;

idx_local = 1:n_local;
idx_hidden = n_local + (1:n_hidden);      % 501:505
idx_global = n_local + n_hidden + 1;      % 506

%% ========================= Dataset generation ============================

noise_variance_fraction = 0.25;
base_seed = 2026;

n_topology_attempts = 18;
n_parameter_draws_per_topology = 360;
n_full_evaluations_per_topology = 12;

%% ========================= H1 node structure =============================

n_anchor_prior = 20;
n_weak_nuisance_prior = 10;
n_prior = n_anchor_prior + n_weak_nuisance_prior;  % 30

n_H1_strong_heldout = 36;
n_H1_weak_heldout = 9;
n_H1_heldout = ...
    n_H1_strong_heldout + ...
    n_H1_weak_heldout;                              % 45

n_H1_total = n_prior + n_H1_heldout;                % 75

H1_anchor_abs_range = [0.46, 0.56];
H1_regular_prior_abs_range = [0.39, 0.49];

H1_strong_heldout_abs_range = [0.35, 0.44];
H1_weak_heldout_abs_range = [0.23, 0.30];

%% ================= Hidden and global node structure ======================

% Number of non-H1 local nodes with elevated global loadings.
n_LV_competitors = 28;

global_background_abs_range = [0.85, 1.05];

global_competitor_shape_range = [0.90, 1.10];
global_competitor_multiplier_range = [5.0, 22.0];

anchor_global_multiplier = 0.12;
weak_prior_global_multiplier = 0.32;

hidden_global_alignment_range = [0.93, 0.98];

hidden_residual_abs_range = [0.70, 1.00];

%% ======================== LL network structure ===========================

n_within_LL_per_group = 2;
n_within_LL = n_groups * n_within_LL_per_group;  % 200
n_between_LL = 400;

forced_H1_cross_fraction = 0.12;
n_forced_H1_cross = round( ...
    forced_H1_cross_fraction * n_between_LL);

within_LL_abs_range = [0.24, 0.43];
between_LL_abs_range = [0.17, 0.34];

group_id = repelem((1:n_groups)', n_nodes_per_group);

all_pairs = nchoosek(1:n_local, 2);

between_pair_mask = ...
    group_id(all_pairs(:, 1)) ~= ...
    group_id(all_pairs(:, 2));

all_between_pairs = all_pairs(between_pair_mask, :);

%% =================== Precision matrix construction =======================

local_diag = 3.0;
hidden_diag = 4.5;
global_diag = 5.0;

spd_margin = 0.10;
numerical_zero_threshold = 1e-10;

%% ======================== Candidate generation ===========================

rho_H1_global_range = [0.10, 0.30];

total_nuisance_to_H1_range = [0.72, 1.10];

global_fraction_of_nuisance_range = [0.65, 0.80];

regular_prior_scale_range = [0.96, 1.10];
heldout_H1_scale_range = [0.96, 1.12];

%% ===================== Joint factor evaluation ===========================

joint_hidden_keep_fractions = [0.20, 0.40, 0.65, 0.85];

joint_max_iterations = 45;
joint_inner_power_iterations = 35;
joint_convergence_tolerance = 1e-6;

%% ================= Latent-factor perturbation evaluation =================

n_LV_perturbations = 24;
LV_latent_mixing_sd = 0.055;
LV_feature_noise_sd = 0.010;

%% ========================== Candidate scoring ============================

target_total_nuisance_to_H1 = 0.90;
target_global_fraction = 0.72;
target_H2H5_to_H1 = 0.25;
target_max_single_H2H5_to_H1 = 0.07;
target_nuisance_rank1_fraction = 0.94;
target_H1_global_absCorr = 0.09;

target_joint_hidden_H1_corr = 0.84;
target_joint_hidden_nuisance_corr = 0.30;
target_joint_hidden_global_corr = 0.30;
target_joint_global_nuisance_corr = 0.88;
target_joint_topK = 0.86;
target_joint_2K = 0.97;

target_LV_topK = 0.50;
target_LV_2K = 0.74;
target_LV_competitor_fraction = 0.47;
target_LV_perturbed_p90 = 0.62;

%% ======================== Candidate selection ============================

preferred_total_nuisance_to_H1 = [0.78, 1.04];
preferred_global_fraction = [0.65, 0.80];
preferred_H2H5_to_H1 = [0.15, 0.35];
preferred_max_single_H2H5_to_H1_max = 0.10;
preferred_nuisance_rank1_fraction = [0.86, 0.985];
preferred_H1_global_absCorr = [0.10, 0.30];

preferred_joint_hidden_H1_corr_min = 0.76;
preferred_joint_hidden_nuisance_corr_max = 0.46;
preferred_joint_hidden_global_corr_max = 0.50;
preferred_joint_global_nuisance_corr_min = 0.76;
preferred_joint_topK = [0.78, 0.94];
preferred_joint_2K_min = 0.92;
preferred_joint_competitor_fraction_max = 0.22;

preferred_LV_topK = [0.38, 0.58];
preferred_LV_2K = [0.55, 0.90];
preferred_LV_competitor_fraction = [0.35, 0.58];
preferred_LV_perturbed_p90_max = 0.68;

%% ======================== Output validation ==============================

essential_total_nuisance_to_H1 = [0.65, 1.18];
essential_global_fraction = [0.58, 0.86];
essential_H2H5_to_H1_max = 0.42;
essential_max_single_H2H5_to_H1_max = 0.13;
essential_nuisance_rank1_fraction_min = 0.80;
essential_H1_global_absCorr_max = 0.34;

essential_joint_hidden_H1_corr_min = 0.68;
essential_joint_hidden_nuisance_corr_max = 0.55;
essential_joint_hidden_global_corr_max = 0.58;
essential_joint_global_nuisance_corr_min = 0.68;
essential_joint_topK_min = 0.72;
essential_joint_2K_min = 0.86;
essential_joint_competitor_fraction_max = 0.32;

essential_LV_topK_max = 0.60;
essential_LV_competitor_fraction_min = 0.30;
essential_LV_perturbed_p90_max = 0.72;

%% ======================== Model parameter files ==========================

% Existing parameter-list files are copied into each output folder.

%% =========================== Dataset repeats =============================

for rep = 1:n_repeats

    OutputFolder = fullfile( ...
        RootOutputFolder, ...
        sprintf('rep_%02d', rep), ...
        'Data');

    if ~exist(OutputFolder, 'dir')
        mkdir(OutputFolder);
    end

    Best = struct();
    best_selection_score = Inf;

    %% ================= Network candidate generation =====================

    for topology_attempt = 1:n_topology_attempts

        rng( ...
            base_seed + rep * 100000 + topology_attempt, ...
            'twister');

        %% ---------------------- H1 node assignment -----------------------

        prior_groups = sort(randperm(n_groups, n_prior));

        prior_indices = zeros(n_prior, 1);

        for j = 1:n_prior

            current_group = prior_groups(j);

            current_group_indices = ...
                ((current_group - 1) * n_nodes_per_group + 1): ...
                (current_group * n_nodes_per_group);

            prior_indices(j) = ...
                current_group_indices(randi(n_nodes_per_group));
        end

        prior_indices = sort(prior_indices(:));

        prior_order = prior_indices(randperm(n_prior));

        anchor_prior_indices = sort( ...
            prior_order(1:n_anchor_prior));

        weak_nuisance_prior_indices = sort( ...
            prior_order( ...
                n_anchor_prior + ...
                (1:n_weak_nuisance_prior)));

        remaining_after_prior = setdiff( ...
            (1:n_local)', ...
            prior_indices);

        heldout_H1_indices = random_subset( ...
            remaining_after_prior, ...
            n_H1_heldout);

        heldout_order = ...
            heldout_H1_indices(randperm(n_H1_heldout));

        strong_heldout_H1_indices = sort( ...
            heldout_order(1:n_H1_strong_heldout));

        weak_heldout_H1_indices = sort( ...
            heldout_order( ...
                n_H1_strong_heldout + ...
                (1:n_H1_weak_heldout)));

        H1_targets = sort([ ...
            prior_indices; ...
            heldout_H1_indices]);

        H1_target_mask = false(n_local, 1);
        H1_target_mask(H1_targets) = true;

        %% -------------------- H1 loading construction --------------------

        H1_base = zeros(n_local, 1);

        H1_base(anchor_prior_indices) = ...
            balanced_random_signs(n_anchor_prior) .* ...
            random_positive_weights( ...
                n_anchor_prior, ...
                H1_anchor_abs_range);

        H1_base(weak_nuisance_prior_indices) = ...
            balanced_random_signs(n_weak_nuisance_prior) .* ...
            random_positive_weights( ...
                n_weak_nuisance_prior, ...
                H1_regular_prior_abs_range);

        H1_base(strong_heldout_H1_indices) = ...
            random_signed_weights( ...
                n_H1_strong_heldout, ...
                H1_strong_heldout_abs_range);

        H1_base(weak_heldout_H1_indices) = ...
            random_signed_weights( ...
                n_H1_weak_heldout, ...
                H1_weak_heldout_abs_range);

        %% --------------- Global-loading node assignment -----------------

        nonH1_pool = find(~H1_target_mask);

        LV_competitor_indices = random_subset( ...
            nonH1_pool, ...
            n_LV_competitors);

        LV_competitor_mask = false(n_local, 1);
        LV_competitor_mask( ...
            LV_competitor_indices) = true;

        %% ------------------ Global loading construction ------------------

        global_background_base = random_signed_weights( ...
            n_local, ...
            global_background_abs_range);

        global_competitor_shape = ...
            random_positive_weights( ...
                n_LV_competitors, ...
                global_competitor_shape_range);

        H1_unit_base = ...
            H1_base / ...
            max(norm(H1_base, 2), eps);

        %% ------------- Additional hidden loading construction -----------

        hidden_residual_basis = zeros(n_local, 4);

        for h = 1:4

            residual = random_signed_weights( ...
                n_local, ...
                hidden_residual_abs_range);

            residual(anchor_prior_indices) = ...
                anchor_global_multiplier * ...
                residual(anchor_prior_indices);

            residual(weak_nuisance_prior_indices) = ...
                weak_prior_global_multiplier * ...
                residual(weak_nuisance_prior_indices);

            residual = orthogonalize_vector( ...
                residual, ...
                H1_unit_base);

            for previous = 1:(h - 1)
                residual = orthogonalize_vector( ...
                    residual, ...
                    hidden_residual_basis(:, previous));
            end

            if norm(residual, 2) <= 1e-10
                error('Hidden residual basis construction failed.');
            end

            hidden_residual_basis(:, h) = ...
                residual / norm(residual, 2);
        end

        %% -------------------- LL precision block -------------------------

        Theta_LL = local_diag * eye(n_local);

        within_edge_list = zeros(n_within_LL, 2);
        within_counter = 0;

        for g = 1:n_groups

            current_group_indices = ...
                ((g - 1) * n_nodes_per_group + 1): ...
                (g * n_nodes_per_group);

            group_pairs = nchoosek(current_group_indices, 2);

            selected = randperm( ...
                size(group_pairs, 1), ...
                n_within_LL_per_group);

            for e = 1:n_within_LL_per_group

                i = group_pairs(selected(e), 1);
                j = group_pairs(selected(e), 2);

                w = random_signed_weight(within_LL_abs_range);

                Theta_LL(i, j) = w;
                Theta_LL(j, i) = w;

                within_counter = within_counter + 1;
                within_edge_list(within_counter, :) = [i, j];
            end
        end

        nonH1_features = find(~H1_target_mask);

        forced_candidates = [];

        for i = 1:numel(H1_targets)

            current_H1 = H1_targets(i);

            valid_nonH1 = nonH1_features( ...
                group_id(nonH1_features) ~= ...
                group_id(current_H1));

            forced_candidates = [ ...
                forced_candidates; ...
                [repmat(current_H1, numel(valid_nonH1), 1), ...
                 valid_nonH1(:)]]; %#ok<AGROW>
        end

        forced_candidates = unique( ...
            sort(forced_candidates, 2), ...
            'rows');

        forced_ids = randperm( ...
            size(forced_candidates, 1), ...
            n_forced_H1_cross);

        forced_pairs = forced_candidates(forced_ids, :);

        remaining_between_candidates = setdiff( ...
            all_between_pairs, ...
            forced_pairs, ...
            'rows');

        remaining_between_count = ...
            n_between_LL - n_forced_H1_cross;

        remaining_ids = randperm( ...
            size(remaining_between_candidates, 1), ...
            remaining_between_count);

        selected_between_pairs = [ ...
            forced_pairs; ...
            remaining_between_candidates(remaining_ids, :)];

        for e = 1:size(selected_between_pairs, 1)

            i = selected_between_pairs(e, 1);
            j = selected_between_pairs(e, 2);

            w = random_signed_weight(between_LL_abs_range);

            Theta_LL(i, j) = w;
            Theta_LL(j, i) = w;
        end

        %% ---------------- Candidate loading generation ------------------

        RawCandidates = repmat( ...
            empty_raw_candidate(), ...
            n_parameter_draws_per_topology, ...
            1);

        for draw = 1:n_parameter_draws_per_topology

            rho_H1_global = random_uniform( ...
                rho_H1_global_range);

            total_nuisance_to_H1_target = ...
                random_uniform( ...
                    total_nuisance_to_H1_range);

            global_fraction_target = ...
                random_uniform( ...
                    global_fraction_of_nuisance_range);

            regular_prior_scale = ...
                random_uniform( ...
                    regular_prior_scale_range);

            heldout_H1_scale = ...
                random_uniform( ...
                    heldout_H1_scale_range);

            hidden_alignments = ...
                hidden_global_alignment_range(1) + ...
                diff(hidden_global_alignment_range) * ...
                rand(4, 1);

            competitor_multiplier = random_uniform( ...
                global_competitor_multiplier_range);

            H1_loading = H1_base;

            H1_loading(weak_nuisance_prior_indices) = ...
                regular_prior_scale * ...
                H1_base(weak_nuisance_prior_indices);

            H1_loading(heldout_H1_indices) = ...
                heldout_H1_scale * ...
                H1_base(heldout_H1_indices);

            H1_unit = ...
                H1_loading / ...
                max(norm(H1_loading, 2), eps);

            global_base = global_background_base;

            global_base(LV_competitor_indices) = ...
                sign_nonzero( ...
                    global_background_base( ...
                        LV_competitor_indices)) .* ...
                competitor_multiplier .* ...
                global_competitor_shape;

            global_base(anchor_prior_indices) = ...
                anchor_global_multiplier * ...
                global_base(anchor_prior_indices);

            global_base(weak_nuisance_prior_indices) = ...
                weak_prior_global_multiplier * ...
                global_base(weak_nuisance_prior_indices);

            global_orthogonal = orthogonalize_vector( ...
                global_base, ...
                H1_unit);

            global_orthogonal = ...
                global_orthogonal / ...
                max(norm(global_orthogonal, 2), eps);

            global_direction = ...
                rho_H1_global * H1_unit + ...
                sqrt(max(1 - rho_H1_global ^ 2, 0)) * ...
                global_orthogonal;

            tiny_floor = 1e-4;

            global_direction( ...
                abs(global_direction) < tiny_floor) = ...
                tiny_floor * sign_nonzero( ...
                    global_direction( ...
                        abs(global_direction) < tiny_floor));

            global_direction = ...
                global_direction / ...
                max(norm(global_direction, 2), eps);

            nuisance_directions = zeros(n_local, 4);

            for h = 1:4

                residual = hidden_residual_basis(:, h);

                residual = orthogonalize_vector( ...
                    residual, ...
                    global_direction);

                residual = ...
                    residual / ...
                    max(norm(residual, 2), eps);

                nuisance_directions(:, h) = ...
                    hidden_alignments(h) * ...
                    global_direction + ...
                    sqrt(max( ...
                        1 - hidden_alignments(h) ^ 2, ...
                        0)) * residual;

                nuisance_directions(:, h) = ...
                    nuisance_directions(:, h) / ...
                    max(norm(nuisance_directions(:, h), 2), eps);
            end

            H1_trace_raw = ...
                sum(H1_loading .^ 2) / hidden_diag;

            total_nuisance_trace_target = ...
                total_nuisance_to_H1_target * ...
                H1_trace_raw;

            global_trace_target = ...
                global_fraction_target * ...
                total_nuisance_trace_target;

            H2H5_trace_target = ...
                total_nuisance_trace_target - ...
                global_trace_target;

            hidden_shares = 0.88 + 0.24 * rand(4, 1);
            hidden_shares = hidden_shares / sum(hidden_shares);

            nuisance_hidden_loadings = zeros(n_local, 4);

            for h = 1:4

                current_trace_target = ...
                    H2H5_trace_target * ...
                    hidden_shares(h);

                current_norm_target = sqrt( ...
                    current_trace_target * hidden_diag);

                nuisance_hidden_loadings(:, h) = ...
                    current_norm_target * ...
                    nuisance_directions(:, h);
            end

            global_norm_target = sqrt( ...
                global_trace_target * global_diag);

            global_loading = ...
                global_norm_target * ...
                global_direction;

            RawD = structural_and_LV_diagnostics( ...
                H1_loading, ...
                nuisance_hidden_loadings, ...
                global_loading, ...
                hidden_diag, ...
                global_diag, ...
                prior_indices, ...
                heldout_H1_indices, ...
                LV_competitor_mask, ...
                0, ...
                0, ...
                0);

            raw_score = raw_candidate_score( ...
                RawD, ...
                target_total_nuisance_to_H1, ...
                target_global_fraction, ...
                target_H2H5_to_H1, ...
                target_max_single_H2H5_to_H1, ...
                target_nuisance_rank1_fraction, ...
                target_H1_global_absCorr, ...
                target_LV_topK, ...
                target_LV_2K, ...
                target_LV_competitor_fraction);

            RawCandidates(draw).rho_H1_global = ...
                rho_H1_global;

            RawCandidates(draw).total_nuisance_to_H1_target = ...
                total_nuisance_to_H1_target;

            RawCandidates(draw).global_fraction_target = ...
                global_fraction_target;

            RawCandidates(draw).regular_prior_scale = ...
                regular_prior_scale;

            RawCandidates(draw).heldout_H1_scale = ...
                heldout_H1_scale;

            RawCandidates(draw).hidden_alignments = ...
                hidden_alignments;

            RawCandidates(draw).competitor_multiplier = ...
                competitor_multiplier;

            RawCandidates(draw).H1_loading = ...
                H1_loading;

            RawCandidates(draw).nuisance_hidden_loadings = ...
                nuisance_hidden_loadings;

            RawCandidates(draw).global_loading = ...
                global_loading;

            RawCandidates(draw).RawDiagnostics = RawD;
            RawCandidates(draw).score = raw_score;
        end

        raw_scores = [RawCandidates.score]';
        [~, raw_order] = sort(raw_scores, 'ascend');

        full_order = raw_order( ...
            1:min(n_full_evaluations_per_topology, ...
                  numel(raw_order)));

        %% ---------------- Candidate matrix evaluation -------------------

        for shortlist_index = 1:numel(full_order)

            Raw = RawCandidates(full_order(shortlist_index));

            Theta_LH = [ ...
                Raw.H1_loading, ...
                Raw.nuisance_hidden_loadings];

            Theta_LG = Raw.global_loading;
            Theta_HH = hidden_diag * eye(n_hidden);

            Model = build_standardized_model( ...
                Theta_LL, ...
                Theta_LH, ...
                Theta_LG, ...
                Theta_HH, ...
                global_diag, ...
                spd_margin, ...
                numerical_zero_threshold);

            H1_loading_final = ...
                Model.Theta(idx_local, idx_hidden(1));

            nuisance_hidden_final = ...
                Model.Theta(idx_local, idx_hidden(2:5));

            global_loading_final = ...
                Model.Theta(idx_local, idx_global);

            hidden_diagonal_final = diag( ...
                Model.Theta(idx_hidden, idx_hidden));

            global_diagonal_final = ...
                Model.Theta(idx_global, idx_global);

            FullD = structural_and_LV_diagnostics( ...
                H1_loading_final, ...
                nuisance_hidden_final, ...
                global_loading_final, ...
                hidden_diagonal_final, ...
                global_diagonal_final, ...
                prior_indices, ...
                heldout_H1_indices, ...
                LV_competitor_mask, ...
                n_LV_perturbations, ...
                LV_latent_mixing_sd, ...
                LV_feature_noise_sd);

            JointD = joint_hidden_global_proxy( ...
                FullD.total_latent_factor, ...
                FullD.H1_factor, ...
                FullD.nuisance_leading_factor, ...
                prior_indices, ...
                heldout_H1_indices, ...
                LV_competitor_mask, ...
                joint_hidden_keep_fractions, ...
                joint_max_iterations, ...
                joint_inner_power_iterations, ...
                joint_convergence_tolerance);

            FullD = merge_structs(FullD, JointD);

            full_score = full_candidate_score( ...
                FullD, ...
                target_total_nuisance_to_H1, ...
                target_global_fraction, ...
                target_H2H5_to_H1, ...
                target_max_single_H2H5_to_H1, ...
                target_nuisance_rank1_fraction, ...
                target_H1_global_absCorr, ...
                target_joint_hidden_H1_corr, ...
                target_joint_hidden_nuisance_corr, ...
                target_joint_hidden_global_corr, ...
                target_joint_global_nuisance_corr, ...
                target_joint_topK, ...
                target_joint_2K, ...
                target_LV_topK, ...
                target_LV_2K, ...
                target_LV_competitor_fraction, ...
                target_LV_perturbed_p90);

            PreferredGatePassed = ...
                in_window( ...
                    FullD.total_nuisance_to_H1_trace_ratio, ...
                    preferred_total_nuisance_to_H1) && ...
                in_window( ...
                    FullD.global_fraction_of_nuisance, ...
                    preferred_global_fraction) && ...
                in_window( ...
                    FullD.H2H5_to_H1_trace_ratio, ...
                    preferred_H2H5_to_H1) && ...
                FullD.max_single_H2H5_to_H1_trace_ratio <= ...
                    preferred_max_single_H2H5_to_H1_max && ...
                in_window( ...
                    FullD.nuisance_rank1_fraction, ...
                    preferred_nuisance_rank1_fraction) && ...
                in_window( ...
                    FullD.H1_global_absCorr, ...
                    preferred_H1_global_absCorr) && ...
                FullD.JointProxy_min_hidden_H1_absCorr >= ...
                    preferred_joint_hidden_H1_corr_min && ...
                FullD.JointProxy_max_hidden_nuisance_absCorr <= ...
                    preferred_joint_hidden_nuisance_corr_max && ...
                FullD.JointProxy_max_hidden_global_absCorr <= ...
                    preferred_joint_hidden_global_corr_max && ...
                FullD.JointProxy_min_global_nuisance_absCorr >= ...
                    preferred_joint_global_nuisance_corr_min && ...
                in_window( ...
                    FullD.JointProxy_min_TopK_H1_recovery, ...
                    preferred_joint_topK) && ...
                FullD.JointProxy_min_2K_H1_recovery >= ...
                    preferred_joint_2K_min && ...
                FullD.JointProxy_max_TopK_competitor_fraction <= ...
                    preferred_joint_competitor_fraction_max && ...
                in_window( ...
                    FullD.LV_exactQuick_TopK_H1_recovery, ...
                    preferred_LV_topK) && ...
                in_window( ...
                    FullD.LV_exactQuick_2K_H1_recovery, ...
                    preferred_LV_2K) && ...
                in_window( ...
                    FullD.LV_exactQuick_TopK_competitor_fraction, ...
                    preferred_LV_competitor_fraction) && ...
                FullD.LV_perturbed_P90_TopK_H1_recovery <= ...
                    preferred_LV_perturbed_p90_max;

            EssentialWriteGatePassed = ...
                in_window( ...
                    FullD.total_nuisance_to_H1_trace_ratio, ...
                    essential_total_nuisance_to_H1) && ...
                in_window( ...
                    FullD.global_fraction_of_nuisance, ...
                    essential_global_fraction) && ...
                FullD.H2H5_to_H1_trace_ratio <= ...
                    essential_H2H5_to_H1_max && ...
                FullD.max_single_H2H5_to_H1_trace_ratio <= ...
                    essential_max_single_H2H5_to_H1_max && ...
                FullD.nuisance_rank1_fraction >= ...
                    essential_nuisance_rank1_fraction_min && ...
                FullD.H1_global_absCorr <= ...
                    essential_H1_global_absCorr_max && ...
                FullD.JointProxy_min_hidden_H1_absCorr >= ...
                    essential_joint_hidden_H1_corr_min && ...
                FullD.JointProxy_max_hidden_nuisance_absCorr <= ...
                    essential_joint_hidden_nuisance_corr_max && ...
                FullD.JointProxy_max_hidden_global_absCorr <= ...
                    essential_joint_hidden_global_corr_max && ...
                FullD.JointProxy_min_global_nuisance_absCorr >= ...
                    essential_joint_global_nuisance_corr_min && ...
                FullD.JointProxy_min_TopK_H1_recovery >= ...
                    essential_joint_topK_min && ...
                FullD.JointProxy_min_2K_H1_recovery >= ...
                    essential_joint_2K_min && ...
                FullD.JointProxy_max_TopK_competitor_fraction <= ...
                    essential_joint_competitor_fraction_max && ...
                FullD.LV_exactQuick_TopK_H1_recovery <= ...
                    essential_LV_topK_max && ...
                FullD.LV_exactQuick_TopK_competitor_fraction >= ...
                    essential_LV_competitor_fraction_min && ...
                FullD.LV_perturbed_P90_TopK_H1_recovery <= ...
                    essential_LV_perturbed_p90_max;

            if PreferredGatePassed
                selection_score = full_score;
            elseif EssentialWriteGatePassed
                selection_score = full_score + 1e4;
            else
                selection_score = full_score + 1e6;
            end

            if selection_score < best_selection_score

                best_selection_score = selection_score;

                Best = struct();

                Best.Model = Model;
                Best.Theta_HH = Theta_HH;

                Best.Diagnostics = FullD;

                Best.PreferredGatePassed = ...
                    PreferredGatePassed;

                Best.EssentialWriteGatePassed = ...
                    EssentialWriteGatePassed;

                Best.selection_score = selection_score;
                Best.raw_score = Raw.score;

                Best.topology_attempt = topology_attempt;

                Best.rho_H1_global = Raw.rho_H1_global;

                Best.total_nuisance_to_H1_target = ...
                    Raw.total_nuisance_to_H1_target;

                Best.global_fraction_target = ...
                    Raw.global_fraction_target;

                Best.regular_prior_scale = ...
                    Raw.regular_prior_scale;

                Best.heldout_H1_scale = ...
                    Raw.heldout_H1_scale;

                Best.hidden_alignments = ...
                    Raw.hidden_alignments;

                Best.competitor_multiplier = ...
                    Raw.competitor_multiplier;

                Best.prior_indices = prior_indices;
                Best.anchor_prior_indices = ...
                    anchor_prior_indices;

                Best.weak_nuisance_prior_indices = ...
                    weak_nuisance_prior_indices;

                Best.heldout_H1_indices = ...
                    heldout_H1_indices;

                Best.strong_heldout_H1_indices = ...
                    strong_heldout_H1_indices;

                Best.weak_heldout_H1_indices = ...
                    weak_heldout_H1_indices;

                Best.H1_targets = H1_targets;

                Best.LV_competitor_indices = ...
                    LV_competitor_indices;

                Best.LV_competitor_mask = ...
                    LV_competitor_mask;
            end
        end
    end

    %% ====================== Candidate validation ========================

    if isempty(fieldnames(Best))
        error('No candidate was evaluated.');
    end
    if require_essential_gate_before_writing && ...
            ~Best.EssentialWriteGatePassed

        error([ ...
            'No candidate passed the essential GT-only write gate. ', ...
            'No observed dataset was written.']);
    end

    %% ================== Selected network structure ======================

    Model = Best.Model;
    prior_indices = Best.prior_indices;

    Idx_h_list = prior_indices - 1;
    Idx_g_list = setdiff((1:n_local)', prior_indices) - 1;

    %% ======================= Sample generation ==========================

    rng(base_seed + rep * 100000 + 90000, 'twister');

    [L_sigma, chol_flag] = chol(Model.Sigma, 'lower');

    if chol_flag ~= 0
        error('Selected covariance matrix is not SPD.');
    end

    Z_clean = randn(n_samples, p) * L_sigma';

    Z_signal = zscore_columns(Z_clean);
    Z_noise = zscore_columns(randn(size(Z_signal)));

    Z_observed = ...
        sqrt(1 - noise_variance_fraction) * Z_signal + ...
        sqrt(noise_variance_fraction) * Z_noise;

    Z_observed = zscore_columns(Z_observed);

    X_local = Z_observed(:, idx_local)';

    %% ========================== Output files ============================

    Theta_full = Model.Theta;

    writematrix( ...
        Theta_full, ...
        fullfile(OutputFolder, 'Theta_full.txt'), ...
        'Delimiter', 'tab');

    writematrix( ...
        Idx_h_list, ...
        fullfile(OutputFolder, 'Idx_h_list.txt'), ...
        'Delimiter', 'tab');

    writematrix( ...
        Idx_g_list, ...
        fullfile(OutputFolder, 'Idx_g_list.txt'), ...
        'Delimiter', 'tab');

    copyfile( ...
        Alpha_list_file, ...
        fullfile(OutputFolder, 'Alpha_list.txt'));

    copyfile( ...
        Lambda_list_file, ...
        fullfile(OutputFolder, 'Lambda_list.txt'));

    write_binary_matrix( ...
        fullfile(OutputFolder, 'Data_whole.bin'), ...
        X_local);
end

%% ========================================================================
% Local functions
%% ========================================================================

function C = empty_raw_candidate()

    C = struct( ...
        'rho_H1_global', NaN, ...
        'total_nuisance_to_H1_target', NaN, ...
        'global_fraction_target', NaN, ...
        'regular_prior_scale', NaN, ...
        'heldout_H1_scale', NaN, ...
        'hidden_alignments', nan(4, 1), ...
        'competitor_multiplier', NaN, ...
        'H1_loading', [], ...
        'nuisance_hidden_loadings', [], ...
        'global_loading', [], ...
        'RawDiagnostics', struct(), ...
        'score', Inf);
end

function value = random_uniform(range)

    value = range(1) + diff(range) * rand();
end

function values = random_subset(vector, count)

    vector = vector(:);

    if count > numel(vector)
        error('Requested subset exceeds the available vector.');
    end

    selected = randperm(numel(vector), count);
    values = sort(vector(selected));
end

function signs = balanced_random_signs(n)

    n_positive = ceil(n / 2);
    n_negative = n - n_positive;

    signs = [ ...
        ones(n_positive, 1); ...
        -ones(n_negative, 1)];

    signs = signs(randperm(n));
end

function values = sign_nonzero(values)

    values = sign(values);
    values(values == 0) = 1;
end

function weights = random_positive_weights(n, abs_range)

    weights = ...
        abs_range(1) + ...
        diff(abs_range) * rand(n, 1);
end

function weight = random_signed_weight(abs_range)

    magnitude = ...
        abs_range(1) + ...
        diff(abs_range) * rand();

    current_sign = 2 * (rand() > 0.5) - 1;

    weight = current_sign * magnitude;
end

function weights = random_signed_weights(n, abs_range)

    magnitudes = ...
        abs_range(1) + ...
        diff(abs_range) * rand(n, 1);

    signs = 2 * (rand(n, 1) > 0.5) - 1;

    weights = signs .* magnitudes;
end

function output = orthogonalize_vector(input, reference)

    input = input(:);
    reference = reference(:);

    denominator = reference' * reference;

    if denominator <= eps
        output = input;
        return;
    end

    output = ...
        input - ...
        reference * ...
        ((reference' * input) / denominator);
end

function Model = build_standardized_model( ...
    Theta_LL, ...
    Theta_LH, ...
    Theta_LG, ...
    Theta_HH, ...
    global_diag, ...
    spd_margin, ...
    numerical_zero_threshold)

    n_local = size(Theta_LL, 1);
    n_hidden = size(Theta_LH, 2);
    n_global = size(Theta_LG, 2);

    p = n_local + n_hidden + n_global;

    idx_local = 1:n_local;
    idx_hidden = n_local + (1:n_hidden);
    idx_global = n_local + n_hidden + (1:n_global);

    Theta_unshifted = zeros(p, p);

    Theta_unshifted(idx_local, idx_local) = Theta_LL;

    Theta_unshifted(idx_local, idx_hidden) = Theta_LH;
    Theta_unshifted(idx_hidden, idx_local) = Theta_LH';

    Theta_unshifted(idx_local, idx_global) = Theta_LG;
    Theta_unshifted(idx_global, idx_local) = Theta_LG';

    Theta_unshifted(idx_hidden, idx_hidden) = Theta_HH;
    Theta_unshifted(idx_global, idx_global) = global_diag;

    Theta_unshifted = ...
        (Theta_unshifted + Theta_unshifted') / 2;

    [~, unshifted_flag] = chol(Theta_unshifted);

    if unshifted_flag == 0

        diagonal_shift = 0;
        Theta_generated = Theta_unshifted;

    else

        try
            minimum_eigenvalue = eigs( ...
                Theta_unshifted, ...
                1, ...
                'smallestreal');
        catch
            minimum_eigenvalue = min(eig(Theta_unshifted));
        end

        diagonal_shift = max( ...
            0, ...
            spd_margin - minimum_eigenvalue);

        Theta_generated = ...
            Theta_unshifted + ...
            diagonal_shift * eye(p);
    end

    Theta_generated = ...
        (Theta_generated + Theta_generated') / 2;

    [~, generated_flag] = chol(Theta_generated);

    if generated_flag ~= 0

        minimum_eigenvalue = min(eig(Theta_generated));

        additional_shift = max( ...
            0, ...
            spd_margin - minimum_eigenvalue);

        Theta_generated = ...
            Theta_generated + ...
            additional_shift * eye(p);

        diagonal_shift = diagonal_shift + additional_shift;
    end

    [~, final_generated_flag] = chol(Theta_generated);

    if final_generated_flag ~= 0
        error('Generated precision matrix is not SPD.');
    end

    Sigma_raw = Theta_generated \ eye(p);
    Sigma_raw = (Sigma_raw + Sigma_raw') / 2;

    sd_vector = sqrt(diag(Sigma_raw));

    if any(~isfinite(sd_vector)) || any(sd_vector <= 0)
        error('Invalid covariance diagonal.');
    end

    Sigma = ...
        Sigma_raw ./ ...
        (sd_vector * sd_vector');

    Sigma = (Sigma + Sigma') / 2;

    Theta = Sigma \ eye(p);
    Theta = (Theta + Theta') / 2;

    Theta(abs(Theta) < numerical_zero_threshold) = 0;

    [~, final_flag] = chol(Theta);

    if final_flag ~= 0
        error('Final standardized precision matrix is not SPD.');
    end

    Model = struct();

    Model.Theta_generated = Theta_generated;
    Model.Sigma_raw = Sigma_raw;
    Model.Sigma = Sigma;
    Model.Theta = Theta;
    Model.diagonal_shift = diagonal_shift;
end

function D = structural_and_LV_diagnostics( ...
    H1_loading, ...
    nuisance_hidden_loadings, ...
    global_loading, ...
    hidden_diagonal, ...
    global_diagonal, ...
    prior_indices, ...
    heldout_H1_indices, ...
    LV_competitor_mask, ...
    n_LV_perturbations, ...
    LV_latent_mixing_sd, ...
    LV_feature_noise_sd)

    H1_loading = H1_loading(:);
    global_loading = global_loading(:);

    if isscalar(hidden_diagonal)
        hidden_diagonal = ...
            hidden_diagonal * ones(5, 1);
    else
        hidden_diagonal = hidden_diagonal(:);
    end

    if numel(hidden_diagonal) ~= 5
        error('hidden_diagonal must contain five values.');
    end

    H1_factor = ...
        H1_loading / ...
        sqrt(max(abs(hidden_diagonal(1)), eps));

    H1_trace = sum(H1_factor .^ 2);

    H2H5_factors = zeros(numel(H1_loading), 4);
    H2H5_trace = zeros(4, 1);

    for h = 1:4

        H2H5_factors(:, h) = ...
            nuisance_hidden_loadings(:, h) / ...
            sqrt(max(abs(hidden_diagonal(h + 1)), eps));

        H2H5_trace(h) = ...
            sum(H2H5_factors(:, h) .^ 2);
    end

    global_factor = ...
        global_loading / ...
        sqrt(max(abs(global_diagonal), eps));

    global_trace = sum(global_factor .^ 2);

    nuisance_factor = [ ...
        H2H5_factors, ...
        global_factor];

    [U_N, S_N, ~] = svd(nuisance_factor, 'econ');

    singular_N = diag(S_N);
    nuisance_eigenvalues = singular_N .^ 2;

    total_nuisance_trace = ...
        sum(nuisance_eigenvalues);

    nuisance_rank1_fraction = ...
        nuisance_eigenvalues(1) / ...
        max(total_nuisance_trace, eps);

    nuisance_leading_factor = ...
        sqrt(nuisance_eigenvalues(1)) * ...
        U_N(:, 1);

    total_nuisance_to_H1 = ...
        total_nuisance_trace / ...
        max(H1_trace, eps);

    H2H5_to_H1 = ...
        sum(H2H5_trace) / ...
        max(H1_trace, eps);

    max_single_H2H5_to_H1 = ...
        max(H2H5_trace) / ...
        max(H1_trace, eps);

    global_fraction_of_nuisance = ...
        global_trace / ...
        max(total_nuisance_trace, eps);

    H1_global_absCorr = safe_abs_corr( ...
        H1_factor, ...
        global_factor);

    total_latent_factor = [ ...
        H1_factor, ...
        H2H5_factors, ...
        global_factor];

    LV = exact_quick_proxy_from_factor( ...
        total_latent_factor, ...
        prior_indices, ...
        heldout_H1_indices, ...
        LV_competitor_mask, ...
        H1_factor);

    perturbed_topK = NaN;
    perturbed_2K = NaN;
    perturbed_p90 = NaN;
    perturbed_max = NaN;

    if n_LV_perturbations > 0

        q = size(total_latent_factor, 2);
        n_local = size(total_latent_factor, 1);

        base_rms = ...
            norm(total_latent_factor, 'fro') / ...
            sqrt(max(n_local * q, 1));

        all_topK = nan(n_LV_perturbations, 1);
        all_2K = nan(n_LV_perturbations, 1);

        for b = 1:n_LV_perturbations

            mixing = ...
                eye(q) + ...
                LV_latent_mixing_sd * ...
                randn(q, q) / sqrt(q);

            feature_noise = ...
                LV_feature_noise_sd * ...
                base_rms * ...
                randn(n_local, q);

            current_factor = ...
                total_latent_factor * mixing + ...
                feature_noise;

            Current = exact_quick_proxy_from_factor( ...
                current_factor, ...
                prior_indices, ...
                heldout_H1_indices, ...
                LV_competitor_mask, ...
                H1_factor);

            all_topK(b) = Current.topK_H1_recovery;
            all_2K(b) = Current.twoK_H1_recovery;
        end

        perturbed_topK = median(all_topK, 'omitnan');
        perturbed_2K = median(all_2K, 'omitnan');
        perturbed_p90 = percentile_linear(all_topK, 90);
        perturbed_max = max(all_topK, [], 'omitnan');
    end

    D = struct();

    D.H1_factor = H1_factor;
    D.global_factor = global_factor;
    D.nuisance_leading_factor = nuisance_leading_factor;
    D.total_latent_factor = total_latent_factor;

    D.H1_trace = H1_trace;
    D.H2H5_trace = H2H5_trace;
    D.global_trace = global_trace;

    D.total_nuisance_to_H1_trace_ratio = ...
        total_nuisance_to_H1;

    D.global_fraction_of_nuisance = ...
        global_fraction_of_nuisance;

    D.H2H5_to_H1_trace_ratio = ...
        H2H5_to_H1;

    D.max_single_H2H5_to_H1_trace_ratio = ...
        max_single_H2H5_to_H1;

    D.nuisance_rank1_fraction = ...
        nuisance_rank1_fraction;

    D.H1_global_absCorr = H1_global_absCorr;

    D.LV_exactQuick_selected_rank = LV.selected_rank;
    D.LV_exactQuick_absCorr_H1 = LV.selected_abs_corr_H1;

    D.LV_exactQuick_TopK_H1_recovery = ...
        LV.topK_H1_recovery;

    D.LV_exactQuick_2K_H1_recovery = ...
        LV.twoK_H1_recovery;

    D.LV_exactQuick_TopK_competitor_fraction = ...
        LV.topK_competitor_fraction;

    D.LV_exactQuick_prior_enrichment = ...
        LV.selected_prior_enrichment;

    D.LV_exactQuick_prior_enrichment_margin = ...
        LV.prior_enrichment_margin;

    D.LV_perturbed_Median_TopK_H1_recovery = ...
        perturbed_topK;

    D.LV_perturbed_Median_2K_H1_recovery = ...
        perturbed_2K;

    D.LV_perturbed_P90_TopK_H1_recovery = ...
        perturbed_p90;

    D.LV_perturbed_Max_TopK_H1_recovery = ...
        perturbed_max;
end

function J = joint_hidden_global_proxy( ...
    total_latent_factor, ...
    H1_factor, ...
    nuisance_leading_factor, ...
    prior_indices, ...
    heldout_H1_indices, ...
    LV_competitor_mask, ...
    keep_fractions, ...
    max_iterations, ...
    inner_power_iterations, ...
    tolerance)

    L_total = ...
        total_latent_factor * ...
        total_latent_factor';

    L_total = (L_total + L_total') / 2;

    prior_block = ...
        L_total(prior_indices, prior_indices);

    prior_block = (prior_block + prior_block') / 2;

    [V_prior, E_prior] = eig(prior_block);

    prior_values = real(diag(E_prior));

    [~, prior_order] = sort( ...
        prior_values, ...
        'descend');

    prior_vector = real(V_prior(:, prior_order(1)));

    hidden_seed = ...
        L_total(:, prior_indices) * ...
        prior_vector;

    hidden_seed = ...
        hidden_seed / ...
        max(norm(hidden_seed, 2), eps);

    global_seed = ...
        nuisance_leading_factor / ...
        max(norm(nuisance_leading_factor, 2), eps);

    n_settings = numel(keep_fractions);

    hidden_H1_corr = zeros(n_settings, 1);
    hidden_nuisance_corr = zeros(n_settings, 1);
    hidden_global_corr = zeros(n_settings, 1);
    global_nuisance_corr = zeros(n_settings, 1);

    topK_recovery = zeros(n_settings, 1);
    twoK_recovery = zeros(n_settings, 1);
    topK_competitor_fraction = zeros(n_settings, 1);

    hidden_support_count = zeros(n_settings, 1);

    for s = 1:n_settings

        keep_fraction = keep_fractions(s);

        h = rank1_factor_update( ...
            L_total, ...
            hidden_seed, ...
            keep_fraction, ...
            inner_power_iterations);

        g = rank1_factor_update( ...
            L_total - h * h', ...
            global_seed, ...
            1.0, ...
            inner_power_iterations);

        for iteration = 1:max_iterations

            h_previous = h;
            g_previous = g;

            h = rank1_factor_update( ...
                L_total - g * g', ...
                h, ...
                keep_fraction, ...
                inner_power_iterations);

            g = rank1_factor_update( ...
                L_total - h * h', ...
                g, ...
                1.0, ...
                inner_power_iterations);

            change = max( ...
                sign_invariant_distance(h, h_previous), ...
                sign_invariant_distance(g, g_previous));

            if change < tolerance
                break;
            end
        end

        hidden_H1_corr(s) = safe_abs_corr( ...
            h, ...
            H1_factor);

        hidden_nuisance_corr(s) = safe_abs_corr( ...
            h, ...
            nuisance_leading_factor);

        hidden_global_corr(s) = safe_abs_corr(h, g);

        global_nuisance_corr(s) = safe_abs_corr( ...
            g, ...
            nuisance_leading_factor);

        Recovery = evaluate_loading_ranking( ...
            abs(h), ...
            prior_indices, ...
            heldout_H1_indices, ...
            LV_competitor_mask);

        topK_recovery(s) = ...
            Recovery.topK_H1_recovery;

        twoK_recovery(s) = ...
            Recovery.twoK_H1_recovery;

        topK_competitor_fraction(s) = ...
            Recovery.topK_competitor_fraction;

        hidden_support_count(s) = ...
            nnz(abs(h) > 1e-10);
    end

    J = struct();

    J.JointProxy_keep_fractions = ...
        keep_fractions(:);

    J.JointProxy_hidden_H1_absCorr_by_setting = ...
        hidden_H1_corr;

    J.JointProxy_hidden_nuisance_absCorr_by_setting = ...
        hidden_nuisance_corr;

    J.JointProxy_hidden_global_absCorr_by_setting = ...
        hidden_global_corr;

    J.JointProxy_global_nuisance_absCorr_by_setting = ...
        global_nuisance_corr;

    J.JointProxy_TopK_H1_recovery_by_setting = ...
        topK_recovery;

    J.JointProxy_2K_H1_recovery_by_setting = ...
        twoK_recovery;

    J.JointProxy_TopK_competitor_fraction_by_setting = ...
        topK_competitor_fraction;

    J.JointProxy_hidden_support_count_by_setting = ...
        hidden_support_count;

    J.JointProxy_min_hidden_H1_absCorr = ...
        min(hidden_H1_corr);

    J.JointProxy_max_hidden_nuisance_absCorr = ...
        max(hidden_nuisance_corr);

    J.JointProxy_max_hidden_global_absCorr = ...
        max(hidden_global_corr);

    J.JointProxy_min_global_nuisance_absCorr = ...
        min(global_nuisance_corr);

    J.JointProxy_min_TopK_H1_recovery = ...
        min(topK_recovery);

    J.JointProxy_min_2K_H1_recovery = ...
        min(twoK_recovery);

    J.JointProxy_max_TopK_competitor_fraction = ...
        max(topK_competitor_fraction);

    J.JointProxy_max_hidden_support_count = ...
        max(hidden_support_count);
end

function factor = rank1_factor_update( ...
    residual_matrix, ...
    initial_vector, ...
    keep_fraction, ...
    max_iterations)

    residual_matrix = ...
        (residual_matrix + residual_matrix') / 2;

    v = initial_vector(:);

    if norm(v, 2) <= eps
        v = randn(size(residual_matrix, 1), 1);
    end

    v = v / norm(v, 2);

    n = numel(v);

    keep_count = max( ...
        1, ...
        min(n, round(keep_fraction * n)));

    for iteration = 1:max_iterations

        y = residual_matrix * v;

        if keep_fraction < 0.999

            absolute_y = abs(y);

            [~, order] = sort( ...
                absolute_y, ...
                'descend');

            mask = false(n, 1);
            mask(order(1:keep_count)) = true;

            % Apply support selection and shrink retained values.
            selected_values = absolute_y(mask);

            if isempty(selected_values)
                threshold = 0;
            else
                threshold = 0.10 * median(selected_values);
            end

            y(~mask) = 0;

            y(mask) = ...
                sign(y(mask)) .* ...
                max(abs(y(mask)) - threshold, 0);
        end

        if norm(y, 2) <= eps
            break;
        end

        y = y / norm(y, 2);

        if sign_invariant_distance(y, v) < 1e-7
            v = y;
            break;
        end

        v = y;
    end

    rayleigh_value = real(v' * residual_matrix * v);
    rayleigh_value = max(rayleigh_value, 0);

    factor = sqrt(rayleigh_value) * v;
end

function distance = sign_invariant_distance(x, y)

    x = x(:);
    y = y(:);

    if norm(x, 2) <= eps && norm(y, 2) <= eps
        distance = 0;
        return;
    end

    x = x / max(norm(x, 2), eps);
    y = y / max(norm(y, 2), eps);

    distance = min( ...
        norm(x - y, 2), ...
        norm(x + y, 2));
end

function R = exact_quick_proxy_from_factor( ...
    Factor, ...
    prior_indices, ...
    heldout_H1_indices, ...
    LV_competitor_mask, ...
    H1_factor)

    n_local = size(Factor, 1);

    [U, S, ~] = svd(Factor, 'econ');

    singular_values = diag(S);
    eigenvalues = singular_values .^ 2;

    threshold = max( ...
        1e-12, ...
        1e-8 * max(eigenvalues));

    keep = eigenvalues > threshold;

    U = U(:, keep);
    eigenvalues = eigenvalues(keep);

    n_components = numel(eigenvalues);

    if n_components < 1
        error('No positive latent component was retained.');
    end

    prior_enrichment = zeros(n_components, 1);
    component_scores = zeros(n_local, n_components);
    component_corr_H1 = zeros(n_components, 1);

    for k = 1:n_components

        feature_score = ...
            sqrt(eigenvalues(k)) * ...
            abs(U(:, k));

        component_scores(:, k) = feature_score;

        feature_score_z = zscore_vector_safe(feature_score);

        prior_enrichment(k) = ...
            mean(feature_score_z(prior_indices));

        component_corr_H1(k) = safe_abs_corr( ...
            U(:, k), ...
            H1_factor);
    end

    [selected_enrichment, selected_rank] = ...
        max(prior_enrichment);

    sorted_enrichment = sort( ...
        prior_enrichment, ...
        'descend');

    if numel(sorted_enrichment) >= 2
        enrichment_margin = ...
            sorted_enrichment(1) - ...
            sorted_enrichment(2);
    else
        enrichment_margin = Inf;
    end

    selected_score = ...
        component_scores(:, selected_rank);

    Ranking = evaluate_loading_ranking( ...
        selected_score, ...
        prior_indices, ...
        heldout_H1_indices, ...
        LV_competitor_mask);

    R = struct();

    R.selected_rank = selected_rank;

    R.selected_abs_corr_H1 = ...
        component_corr_H1(selected_rank);

    R.topK_H1_recovery = ...
        Ranking.topK_H1_recovery;

    R.twoK_H1_recovery = ...
        Ranking.twoK_H1_recovery;

    R.topK_competitor_fraction = ...
        Ranking.topK_competitor_fraction;

    R.selected_prior_enrichment = ...
        selected_enrichment;

    R.prior_enrichment_margin = ...
        enrichment_margin;
end

function R = evaluate_loading_ranking( ...
    score, ...
    prior_indices, ...
    heldout_H1_indices, ...
    LV_competitor_mask)

    n_local = numel(score);

    candidate_indices = setdiff( ...
        (1:n_local)', ...
        prior_indices(:));

    [~, order] = sort( ...
        abs(score(candidate_indices)), ...
        'descend');

    ranked_candidates = candidate_indices(order);

    K = numel(heldout_H1_indices);

    heldout_mask = false(n_local, 1);
    heldout_mask(heldout_H1_indices) = true;

    topK_count = min(K, numel(ranked_candidates));
    twoK_count = min(2 * K, numel(ranked_candidates));

    topK_indices = ranked_candidates(1:topK_count);

    topK_H1_recovery = ...
        sum(heldout_mask(topK_indices)) / K;

    twoK_H1_recovery = ...
        sum(heldout_mask( ...
            ranked_candidates(1:twoK_count))) / K;

    topK_competitor_fraction = ...
        sum(LV_competitor_mask(topK_indices)) / ...
        max(topK_count, 1);

    R = struct();

    R.topK_H1_recovery = topK_H1_recovery;
    R.twoK_H1_recovery = twoK_H1_recovery;

    R.topK_competitor_fraction = ...
        topK_competitor_fraction;
end

function score = raw_candidate_score( ...
    D, ...
    target_total_nuisance_to_H1, ...
    target_global_fraction, ...
    target_H2H5_to_H1, ...
    target_max_single_H2H5_to_H1, ...
    target_nuisance_rank1_fraction, ...
    target_H1_global_absCorr, ...
    target_LV_topK, ...
    target_LV_2K, ...
    target_LV_competitor_fraction)

    score = ...
        8.0 * abs( ...
            D.total_nuisance_to_H1_trace_ratio - ...
            target_total_nuisance_to_H1) + ...
        8.0 * abs( ...
            D.global_fraction_of_nuisance - ...
            target_global_fraction) + ...
        8.0 * abs( ...
            D.H2H5_to_H1_trace_ratio - ...
            target_H2H5_to_H1) + ...
        10.0 * abs( ...
            D.max_single_H2H5_to_H1_trace_ratio - ...
            target_max_single_H2H5_to_H1) + ...
        8.0 * abs( ...
            D.nuisance_rank1_fraction - ...
            target_nuisance_rank1_fraction) + ...
        7.0 * abs( ...
            D.H1_global_absCorr - ...
            target_H1_global_absCorr) + ...
        18.0 * abs( ...
            D.LV_exactQuick_TopK_H1_recovery - ...
            target_LV_topK) + ...
        8.0 * abs( ...
            D.LV_exactQuick_2K_H1_recovery - ...
            target_LV_2K) + ...
        12.0 * abs( ...
            D.LV_exactQuick_TopK_competitor_fraction - ...
            target_LV_competitor_fraction);

    if D.LV_exactQuick_TopK_H1_recovery > 0.60
        score = score + ...
            180.0 * ...
            (D.LV_exactQuick_TopK_H1_recovery - 0.60);
    end
end

function score = full_candidate_score( ...
    D, ...
    target_total_nuisance_to_H1, ...
    target_global_fraction, ...
    target_H2H5_to_H1, ...
    target_max_single_H2H5_to_H1, ...
    target_nuisance_rank1_fraction, ...
    target_H1_global_absCorr, ...
    target_joint_hidden_H1_corr, ...
    target_joint_hidden_nuisance_corr, ...
    target_joint_hidden_global_corr, ...
    target_joint_global_nuisance_corr, ...
    target_joint_topK, ...
    target_joint_2K, ...
    target_LV_topK, ...
    target_LV_2K, ...
    target_LV_competitor_fraction, ...
    target_LV_perturbed_p90)

    score = raw_candidate_score( ...
        D, ...
        target_total_nuisance_to_H1, ...
        target_global_fraction, ...
        target_H2H5_to_H1, ...
        target_max_single_H2H5_to_H1, ...
        target_nuisance_rank1_fraction, ...
        target_H1_global_absCorr, ...
        target_LV_topK, ...
        target_LV_2K, ...
        target_LV_competitor_fraction);

    score = score + ...
        12.0 * abs( ...
            D.JointProxy_min_hidden_H1_absCorr - ...
            target_joint_hidden_H1_corr) + ...
        12.0 * abs( ...
            D.JointProxy_max_hidden_nuisance_absCorr - ...
            target_joint_hidden_nuisance_corr) + ...
        14.0 * abs( ...
            D.JointProxy_max_hidden_global_absCorr - ...
            target_joint_hidden_global_corr) + ...
        10.0 * abs( ...
            D.JointProxy_min_global_nuisance_absCorr - ...
            target_joint_global_nuisance_corr) + ...
        18.0 * abs( ...
            D.JointProxy_min_TopK_H1_recovery - ...
            target_joint_topK) + ...
        8.0 * abs( ...
            D.JointProxy_min_2K_H1_recovery - ...
            target_joint_2K) + ...
        10.0 * abs( ...
            D.LV_perturbed_P90_TopK_H1_recovery - ...
            target_LV_perturbed_p90);

    if D.JointProxy_max_hidden_global_absCorr > 0.58
        score = score + ...
            200.0 * ...
            (D.JointProxy_max_hidden_global_absCorr - 0.58);
    end

    if D.JointProxy_min_TopK_H1_recovery < 0.72
        score = score + ...
            180.0 * ...
            (0.72 - D.JointProxy_min_TopK_H1_recovery);
    end
end

function output = merge_structs(A, B)

    output = A;

    fields = fieldnames(B);

    for i = 1:numel(fields)
        output.(fields{i}) = B.(fields{i});
    end
end

function value = safe_abs_corr(x, y)

    x = x(:);
    y = y(:);

    if std(x) <= eps || std(y) <= eps
        value = 0;
        return;
    end

    value = abs(corr( ...
        x, ...
        y, ...
        'Type', 'Pearson', ...
        'Rows', 'complete'));
end

function z = zscore_vector_safe(x)

    x = x(:);

    mu = mean(x);
    sigma = std(x, 0);

    if ~isfinite(sigma) || sigma <= eps
        z = zeros(size(x));
    else
        z = (x - mu) / sigma;
    end
end

function value = percentile_linear(x, percentile_value)

    x = x(:);
    x = x(isfinite(x));

    if isempty(x)
        value = NaN;
        return;
    end

    x = sort(x, 'ascend');

    if numel(x) == 1
        value = x;
        return;
    end

    position = ...
        1 + ...
        (percentile_value / 100) * ...
        (numel(x) - 1);

    lower_index = floor(position);
    upper_index = ceil(position);

    if lower_index == upper_index
        value = x(lower_index);
    else
        weight = position - lower_index;

        value = ...
            (1 - weight) * x(lower_index) + ...
            weight * x(upper_index);
    end
end

function tf = in_window(value, window)

    tf = value >= window(1) && value <= window(2);
end

function Z = zscore_columns(X)

    means = mean(X, 1);
    sds = std(X, 0, 1);

    sds(sds == 0) = 1;

    Z = (X - means) ./ sds;
end


function write_binary_matrix(filename, Matrix)

    fid = fopen(filename, 'wb');

    if fid == -1
        error('Cannot open binary file: %s', filename);
    end

    fwrite(fid, uint64(size(Matrix, 1)), 'uint64');
    fwrite(fid, uint64(size(Matrix, 2)), 'uint64');

    % Transpose before writing to preserve the expected row-major layout.
    fwrite(fid, Matrix.', 'double');

    fclose(fid);
end
